version: 2

builds:
  # You can have multiple builds defined as a yaml list
  - #
    # ID of the build.
    #
    # Default: Project directory name
    id: "pingcli"

    # Binary name.
    # Can be a path (e.g. `bin/app`) to wrap the binary in a directory.
    #
    # Default: Project directory name
    binary: pingcli

    # Custom environment variables to be set during the builds.
    # Invalid environment variables will be ignored.
    # For more info refer to: https://pkg.go.dev/cmd/go#hdr-Environment_variables
    #
    # Default: os.Environ() ++ env config section.
    # Templates: allowed.
    env:
      - CGO_ENABLED=0

    # GOOS list to build for.
    # For more info refer to: https://golang.org/doc/install/source#environment
    # Choices for $GOOS are android, darwin, dragonfly, freebsd, illumos, ios, js, linux, netbsd, openbsd, plan9, solaris, wasip1, and windows.
    #
    # Default: [ 'darwin', 'linux', 'windows' ]
    goos:
      - darwin
      - linux
      - windows

    # GOARCH to build for.
    # For more info refer to: https://golang.org/doc/install/source#environment
    # Choices for $GOARCH are amd64 (64-bit x86, the most mature port), 386 (32-bit x86), arm (32-bit ARM), arm64 (64-bit ARM), ppc64le (PowerPC 64-bit, little-endian), ppc64 (PowerPC 64-bit, big-endian), mips64le (MIPS 64-bit, little-endian), mips64 (MIPS 64-bit, big-endian), mipsle (MIPS 32-bit, little-endian), mips (MIPS 32-bit, big-endian), s390x (IBM System z 64-bit, big-endian), and wasm (WebAssembly 32-bit).
    #
    # Default: [ '386', 'amd64', 'arm64' ]
    goarch:
      - "386"
      - amd64
      - arm64

nfpms:
  # note that this is an array of nfpm configs
  - #
    # ID of the nfpm config, must be unique.
    #
    # Default: 'default'.
    id: pingcli

    # Name of the package.
    #
    # Default: ProjectName.
    # Templates: allowed.
    package_name: pingcli

    # Your app's vendor.
    vendor: Ping Identity

    # Your app's homepage.
    #
    # Default: inferred from global metadata.
    homepage: https://github.com/wesleymccollam/pingcli-test

    # Your app's maintainer (probably you).
    #
    # Default: inferred from global metadata.
    maintainer: Ping Identity

    # Your app's description.
    #
    # Default: inferred from global metadata.
    description: "The Ping CLI is a unified command line interface for configuring and managing Ping Identity Services."

    # Your app's license.
    #
    # Default: inferred from global metadata.
    license: Apache 2.0

    # Formats to be generated.
    formats:
      - apk
      - deb
      - rpm

    # Custom configuration applied only to the RPM packager.
    rpm:
      # The package summary.
      #
      # Default: first line of the description.
      summary: The Ping CLI is a unified command line interface for configuring and managing Ping Identity Services.

      # The packager is used to identify the organization that actually packaged
      # the software, as opposed to the author of the software.
      # `maintainer` will be used as fallback if not specified.
      # This will expand any env var you set in the field, eg packager: ${PACKAGER}
      packager: Ping Identity

    # Custom configuration applied only to the Deb packager.
    deb:
      # Additional fields for the control file. Empty fields are ignored.
      # This will expand any env vars you set in the field values, e.g. Vcs-Browser: ${CI_PROJECT_URL}
      fields:
        Bugs: https://github.com/wesleymccollam/pingcli-test/issues

    apk:
      # The package is signed if a key_file is set
      signature:
        # The name of the signing key. When verifying a package, the signature
        # is matched to the public key store in /etc/apk/keys/<key_name>.rsa.pub.
        #
        # Default: maintainer's email address.
        # Templates: allowed.
        key_name: origin

    archlinux:
      # The pkgbase can be used to explicitly specify the name to be used to refer
      # to a group of packages. See: https://wiki.archlinux.org/title/PKGBUILD#pkgbase.
      pkgbase: pingcli

      # The packager refers to the organization packaging the software, not to be confused
      # with the maintainer, which is the person who maintains the software.
      packager: Ping Identity

release:
  # If set to auto, will mark the release as not ready for production
  # in case there is an indicator for this in the tag e.g. v1.0.0-rc1
  # If set to true, will mark the release as not ready for production.
  # Default is false.
  prerelease: auto

  # If set to false, will NOT mark the release as "latest".
  # This prevents it from being shown at the top of the release list,
  # and from being returned when calling https://api.github.com/repos/OWNER/REPO/releases/latest.
  #
  # Available only for GitHub.
  #
  # Default is true.
  # Since: v1.20
  make_latest: true

  # What to do with the release notes in case there the release already exists.
  #
  # Valid options are:
  # - `keep-existing`: keep the existing notes
  # - `append`: append the current release notes to the existing notes
  # - `prepend`: prepend the current release notes to the existing notes
  # - `replace`: replace existing notes
  #
  # Default is `keep-existing`.
  mode: append

checksum:
  # Algorithm to be used.
  #
  # Accepted options are:
  # - sha256
  # - sha512
  # - sha1
  # - crc32
  # - md5
  # - sha224
  # - sha384
  # - sha3-256
  # - sha3-512
  # - sha3-224
  # - sha3-384
  # - blake2s
  # - blake2b
  #
  # Default: 'sha256'.
  algorithm: sha256

  # If true, will create one checksum file for each artifact.
  split: true

  # Disable the generation/upload of the checksum file.
  disable: false

dockers:
  - image_templates:
      - "wesleymccollam/pingcli:{{ .Tag }}-amd64"
    use: buildx
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--pull"
  - image_templates:
      - "wesleymccollam/pingcli:{{ .Tag }}-arm64"
    use: buildx
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--pull"
docker_manifests:
  - name_template: "wesleymccollam/pingcli:latest"
    image_templates:
      - "wesleymccollam/pingcli:{{ .Tag }}-amd64"
      - "wesleymccollam/pingcli:{{ .Tag }}-arm64"
  - name_template: "wesleymccollam/pingcli:{{ .Tag }}"
    image_templates:
      - "wesleymccollam/pingcli:{{ .Tag }}-amd64"
      - "wesleymccollam/pingcli:{{ .Tag }}-arm64"

signs:
  - artifacts: checksum
