// Copyright © 2025 Ping Identity Corporation
// Code generated by ping-cli-generator

package pingfederate_testable_resources

import (
	"testing"

	"github.com/pingidentity/pingcli/internal/connector"
	"github.com/pingidentity/pingcli/internal/connector/common"
	"github.com/pingidentity/pingcli/internal/connector/pingfederate/resources"
	"github.com/pingidentity/pingcli/internal/testing/testutils_resource"
	"github.com/pingidentity/pingcli/internal/utils"
	client "github.com/pingidentity/pingfederate-go-client/v1220/configurationapi"
)

func IdpAdapter(t *testing.T, clientInfo *connector.ClientInfo) *testutils_resource.TestableResource {
	t.Helper()

	return &testutils_resource.TestableResource{
		ClientInfo: clientInfo,
		CreateFunc: createIdpAdapter,
		DeleteFunc: deleteIdpAdapter,
		Dependencies: []*testutils_resource.TestableResource{
			PasswordCredentialValidator(t, clientInfo),
		},
		ExportableResource: resources.IdpAdapter(clientInfo),
	}
}

func createIdpAdapter(t *testing.T, clientInfo *connector.ClientInfo, resourceType string, strArgs ...string) testutils_resource.ResourceInfo {
	t.Helper()

	if len(strArgs) != 1 {
		t.Errorf("Unexpected number of arguments provided to createIdpAdapter(): %v", strArgs)

		return testutils_resource.ResourceInfo{}
	}
	pcvId := strArgs[0]

	request := clientInfo.PingFederateApiClient.IdpAdaptersAPI.CreateIdpAdapter(clientInfo.PingFederateContext)
	clientStruct := client.IdpAdapter{
		Id:   "testIdpAdapterId",
		Name: "testIdpAdapterName",
		PluginDescriptorRef: client.ResourceLink{
			Id: "com.pingidentity.adapters.httpbasic.idp.HttpBasicIdpAuthnAdapter",
		},
		Configuration: client.PluginConfiguration{
			Tables: []client.ConfigTable{
				{
					Name: "Credential Validators",
					Rows: []client.ConfigRow{
						{
							Fields: []client.ConfigField{
								{
									Name:  "Password Credential Validator Instance",
									Value: utils.Pointer(pcvId),
								},
							},
							DefaultRow: utils.Pointer(false),
						},
					},
				},
			},
			Fields: []client.ConfigField{
				{
					Name:  "Realm",
					Value: utils.Pointer("testRealmName"),
				},
			},
		},
		AttributeContract: &client.IdpAdapterAttributeContract{
			CoreAttributes: []client.IdpAdapterAttribute{
				{
					Name:      "username",
					Masked:    utils.Pointer(false),
					Pseudonym: utils.Pointer(true),
				},
			},
		},
		AttributeMapping: &client.IdpAdapterContractMapping{
			AttributeContractFulfillment: map[string]client.AttributeFulfillmentValue{
				"username": {
					Source: client.SourceTypeIdKey{
						Type: "ADAPTER",
					},
					Value: "username",
				},
			},
		},
	}

	request = request.Body(clientStruct)

	resource, response, err := request.Execute()
	ok, err := common.HandleClientResponse(response, err, "CreateIdpAdapter", resourceType)
	if err != nil {
		t.Errorf("Failed to execute client function\nResponse Status: %s\nResponse Body: %s\nError: %v", response.Status, response.Body, err)

		return testutils_resource.ResourceInfo{}
	}
	if !ok {
		t.Errorf("Failed to execute client function\nResponse Status: %s\nResponse Body: %s", response.Status, response.Body)

		return testutils_resource.ResourceInfo{}
	}

	return testutils_resource.ResourceInfo{
		DeletionIds: []string{
			resource.Id,
		},
		CreationInfo: map[testutils_resource.ResourceCreationInfoType]string{
			testutils_resource.ENUM_ID:   resource.Id,
			testutils_resource.ENUM_NAME: resource.Name,
		},
	}
}

func deleteIdpAdapter(t *testing.T, clientInfo *connector.ClientInfo, resourceType string, ids ...string) {
	t.Helper()

	if len(ids) != 1 {
		t.Errorf("Unexpected number of arguments provided to deleteIdpAdapter(): %v", ids)

		return
	}

	request := clientInfo.PingFederateApiClient.IdpAdaptersAPI.DeleteIdpAdapter(clientInfo.PingFederateContext, ids[0])

	response, err := request.Execute()
	ok, err := common.HandleClientResponse(response, err, "DeleteIdpAdapter", resourceType)
	if err != nil {
		t.Errorf("Failed to execute client function\nResponse Status: %s\nResponse Body: %s\nError: %v", response.Status, response.Body, err)

		return
	}
	if !ok {
		t.Errorf("Failed to execute client function\nResponse Status: %s\nResponse Body: %s", response.Status, response.Body)

		return
	}
}
