// Copyright © 2025 Ping Identity Corporation
// Code generated by ping-cli-generator

package pingfederate_testable_resources

import (
	"testing"

	"github.com/pingidentity/pingcli/internal/connector"
	"github.com/pingidentity/pingcli/internal/connector/common"
	"github.com/pingidentity/pingcli/internal/connector/pingfederate/resources"
	"github.com/pingidentity/pingcli/internal/testing/testutils_resource"
	"github.com/pingidentity/pingcli/internal/utils"
	client "github.com/pingidentity/pingfederate-go-client/v1220/configurationapi"
)

func IdpSpConnection(t *testing.T, clientInfo *connector.ClientInfo) *testutils_resource.TestableResource {
	t.Helper()

	return &testutils_resource.TestableResource{
		ClientInfo: clientInfo,
		CreateFunc: createIdpSpConnection,
		DeleteFunc: deleteIdpSpConnection,
		Dependencies: []*testutils_resource.TestableResource{
			KeypairsSigningKey(t, clientInfo),
			IdpTokenProcessor(t, clientInfo),
		},
		ExportableResource: resources.IdpSpConnection(clientInfo),
	}
}

func createIdpSpConnection(t *testing.T, clientInfo *connector.ClientInfo, resourceType string, strArgs ...string) testutils_resource.ResourceInfo {
	t.Helper()

	if len(strArgs) != 3 {
		t.Errorf("Unexpected number of arguments provided to createIdpSpConnection(): %v", strArgs)

		return testutils_resource.ResourceInfo{}
	}
	signingKeyPairId := strArgs[0]
	idpTokenProcessorId := strArgs[2]

	request := clientInfo.PingFederateApiClient.IdpSpConnectionsAPI.CreateSpConnection(clientInfo.PingFederateContext)
	clientStruct := client.SpConnection{
		Connection: client.Connection{
			Active: utils.Pointer(true),
			Credentials: &client.ConnectionCredentials{
				SigningSettings: &client.SigningSettings{
					Algorithm:                utils.Pointer("SHA256withRSA"),
					IncludeCertInSignature:   utils.Pointer(false),
					IncludeRawKeyInSignature: utils.Pointer(false),
					SigningKeyPairRef: client.ResourceLink{
						Id: signingKeyPairId,
					},
				},
			},
			EntityId:    "TestEntityId",
			Id:          utils.Pointer("TestSpConnectionId"),
			LoggingMode: utils.Pointer("STANDARD"),
			Name:        "TestSpConnectionName",
			Type:        utils.Pointer("SP"),
		},
		WsTrust: &client.SpWsTrust{
			AttributeContract: client.SpWsTrustAttributeContract{
				CoreAttributes: []client.SpWsTrustAttribute{
					{
						Name: "TOKEN_SUBJECT",
					},
				},
			},
			DefaultTokenType:       utils.Pointer("SAML20"),
			EncryptSaml2Assertion:  utils.Pointer(false),
			GenerateKey:            utils.Pointer(false),
			MinutesBefore:          utils.Pointer(int64(5)),
			MinutesAfter:           utils.Pointer(int64(30)),
			OAuthAssertionProfiles: utils.Pointer(false),
			PartnerServiceIds: []string{
				"TestIdentifier",
			},
			TokenProcessorMappings: []client.IdpTokenProcessorMapping{
				{
					AttributeContractFulfillment: map[string]client.AttributeFulfillmentValue{
						"TOKEN_SUBJECT": {
							Source: client.SourceTypeIdKey{
								Type: "NO_MAPPING",
							},
						},
					},
					IdpTokenProcessorRef: client.ResourceLink{
						Id: idpTokenProcessorId,
					},
				},
			},
		},
		ConnectionTargetType: utils.Pointer("STANDARD"),
	}

	request = request.Body(clientStruct)

	resource, response, err := request.Execute()
	ok, err := common.HandleClientResponse(response, err, "CreateSpConnection", resourceType)
	if err != nil {
		t.Errorf("Failed to execute client function\nResponse Status: %s\nResponse Body: %s\nError: %v", response.Status, response.Body, err)

		return testutils_resource.ResourceInfo{}
	}
	if !ok {
		t.Errorf("Failed to execute client function\nResponse Status: %s\nResponse Body: %s", response.Status, response.Body)

		return testutils_resource.ResourceInfo{}
	}

	return testutils_resource.ResourceInfo{
		DeletionIds: []string{
			*resource.Id,
		},
		CreationInfo: map[testutils_resource.ResourceCreationInfoType]string{
			testutils_resource.ENUM_ID:   *resource.Id,
			testutils_resource.ENUM_NAME: resource.Name,
		},
	}
}

func deleteIdpSpConnection(t *testing.T, clientInfo *connector.ClientInfo, resourceType string, ids ...string) {
	t.Helper()

	if len(ids) != 1 {
		t.Errorf("Unexpected number of arguments provided to deleteIdpSpConnection(): %v", ids)

		return
	}

	request := clientInfo.PingFederateApiClient.IdpSpConnectionsAPI.DeleteSpConnection(clientInfo.PingFederateContext, ids[0])

	response, err := request.Execute()
	ok, err := common.HandleClientResponse(response, err, "DeleteSpConnection", resourceType)
	if err != nil {
		t.Errorf("Failed to execute client function\nResponse Status: %s\nResponse Body: %s\nError: %v", response.Status, response.Body, err)

		return
	}
	if !ok {
		t.Errorf("Failed to execute client function\nResponse Status: %s\nResponse Body: %s", response.Status, response.Body)

		return
	}
}
