// Copyright © 2025 Ping Identity Corporation
// Code generated by ping-cli-generator

package pingfederate_testable_resources

import (
	"testing"

	"github.com/pingidentity/pingcli/internal/connector"
	"github.com/pingidentity/pingcli/internal/connector/common"
	"github.com/pingidentity/pingcli/internal/testing/testutils_resource"
	"github.com/pingidentity/pingcli/internal/utils"
	client "github.com/pingidentity/pingfederate-go-client/v1220/configurationapi"
)

func OauthTokenExchangeProcessorPolicy(t *testing.T, clientInfo *connector.ClientInfo) *testutils_resource.TestableResource {
	t.Helper()

	return &testutils_resource.TestableResource{
		ClientInfo: clientInfo,
		CreateFunc: createOauthTokenExchangeProcessorPolicy,
		DeleteFunc: deleteOauthTokenExchangeProcessorPolicy,
		Dependencies: []*testutils_resource.TestableResource{
			IdpTokenProcessor(t, clientInfo),
		},
		ExportableResource: nil,
	}
}

func createOauthTokenExchangeProcessorPolicy(t *testing.T, clientInfo *connector.ClientInfo, resourceType string, strArgs ...string) testutils_resource.ResourceInfo {
	t.Helper()

	if len(strArgs) != 2 {
		t.Errorf("Unexpected number of arguments provided to createOauthTokenExchangeProcessorPolicy(): %v", strArgs)

		return testutils_resource.ResourceInfo{}
	}
	testTokenProcessorId := strArgs[1]

	request := clientInfo.PingFederateApiClient.OauthTokenExchangeProcessorAPI.CreateOauthTokenExchangeProcessorPolicy(clientInfo.PingFederateContext)
	result := client.TokenExchangeProcessorPolicy{
		ActorTokenRequired: utils.Pointer(false),
		AttributeContract: client.TokenExchangeProcessorAttributeContract{
			CoreAttributes: []client.TokenExchangeProcessorAttribute{
				{
					Name: "subject",
				},
			},
		},
		Id:   "TestProcessorPolicyId",
		Name: "TestProcessorPolicyName",
		ProcessorMappings: []client.TokenExchangeProcessorMapping{
			{
				AttributeContractFulfillment: map[string]client.AttributeFulfillmentValue{
					"subject": {
						Source: client.SourceTypeIdKey{
							Type: "NO_MAPPING",
						},
					},
				},
				SubjectTokenType: "TestTokenType",
				SubjectTokenProcessor: client.ResourceLink{
					Id: testTokenProcessorId,
				},
			},
		},
	}

	request = request.Body(result)

	resource, response, err := request.Execute()
	ok, err := common.HandleClientResponse(response, err, "CreateOauthTokenExchangeProcessorPolicy", resourceType)
	if err != nil {
		t.Errorf("Failed to execute client function\nResponse Status: %s\nResponse Body: %s\nError: %v", response.Status, response.Body, err)

		return testutils_resource.ResourceInfo{}
	}
	if !ok {
		t.Errorf("Failed to execute client function\nResponse Status: %s\nResponse Body: %s", response.Status, response.Body)

		return testutils_resource.ResourceInfo{}
	}

	return testutils_resource.ResourceInfo{
		DeletionIds: []string{
			resource.Id,
		},
		CreationInfo: map[testutils_resource.ResourceCreationInfoType]string{
			testutils_resource.ENUM_ID: resource.Id,
		},
	}
}

func deleteOauthTokenExchangeProcessorPolicy(t *testing.T, clientInfo *connector.ClientInfo, resourceType string, ids ...string) {
	t.Helper()

	if len(ids) != 1 {
		t.Errorf("Unexpected number of arguments provided to deleteOauthTokenExchangeProcessorPolicy(): %v", ids)

		return
	}

	request := clientInfo.PingFederateApiClient.OauthTokenExchangeProcessorAPI.DeleteOauthTokenExchangeProcessorPolicyy(clientInfo.PingFederateContext, ids[0])

	response, err := request.Execute()
	ok, err := common.HandleClientResponse(response, err, "DeleteOauthTokenExchangeProcessorPolicy", resourceType)
	if err != nil {
		t.Errorf("Failed to execute client function\nResponse Status: %s\nResponse Body: %s\nError: %v", response.Status, response.Body, err)

		return
	}
	if !ok {
		t.Errorf("Failed to execute client function\nResponse Status: %s\nResponse Body: %s", response.Status, response.Body)

		return
	}
}
