= pingcli config
:created-date: September 18, 2026
:revdate: June 5, 2026
:resourceid: pingcli_command_reference_pingcli_config

Manage the CLI configuration.

== Synopsis

Manage the configuration of the CLI, including Ping product connection parameters.

The Ping CLI supports the use of configuration profiles.
Configuration profiles can be used when connecting to multiple environments using the same Ping CLI instance, such as when managing multiple development or demonstration environments.

A pre-defined default profile will be used to store the configuration of the CLI.
Additional custom profiles can be created using the `pingcli config profiles add` command.
To use a custom profile, the `--profile` flag can be used on supported commands to specify the profile to use for that command.
To set a custom profile as the default, use the `pingcli config profiles set-active` command.

----
pingcli config
----

== Options

----
  -U, --unmask-values   Unmask secret values. (default false)
  -h, --help            help for config
----

== Options inherited from parent commands

----
  -C, --config string           The relative or full path to a custom Ping CLI configuration file. (default $HOME/.pingcli/config.yaml)
  -D, --detailed-exitcode       Enable detailed exit code output. (default false) 0 - pingcli command succeeded with no errors or warnings. 1 - pingcli command failed with errors. 2 - pingcli command succeeded with warnings.
  -O, --output-format string    Specify the console output format. (default text) Options are: json, ndjson, ndjson-wrapped, text.
  -P, --profile string          The name of a configuration profile to use.
      --debug                   Enable debug output for error messages, including stack traces and transaction IDs. (default false)
      --log-file string         Write logs to a file at the given path. File logging is disabled when not set.
      --log-file-level string   Set the file log level. Options are: DEBUG, INFO, WARN, ERROR. (default DEBUG)
      --log-level string        Set the console log level. Options are: DEBUG, INFO, WARN, ERROR. (default WARN)
      --no-color                Disable text output in color. (default false)
      --query string            JMESPath expression to filter JSON output. Requires -O json, ndjson, or ndjson-wrapped. Example: --query 'data[?enabled].name'
----

== More information

* xref:pingcli.adoc[]	 - A CLI tool for managing the configuration of Ping Identity products.

== Subcommands

* xref:pingcli_config_get.adoc[] - Read stored configuration settings for the CLI.
* xref:pingcli_config_list-keys.adoc[] - List all configuration keys.
* xref:pingcli_config_profiles.adoc[] - Manage the configuration profiles.
* xref:pingcli_config_set.adoc[] - Set stored configuration settings for the CLI.
* xref:pingcli_config_unset.adoc[] - Unset stored configuration settings for the CLI.
