= pingcli authorize application-roles app-role-permissions
:created-date: June 8, 2026
:revdate: June 8, 2026
:resourceid: pingcli_command_reference_pingcli_authorize_application-roles_app-role-permissions

Application Role Permissions

== Synopsis

Application Role Permissions

----
pingcli authorize application-roles app-role-permissions [flags]
----

== Options inherited from parent commands

----
  -C, --config string           The relative or full path to a custom Ping CLI configuration file. (default $HOME/.pingcli/config.yaml)
  -D, --detailed-exitcode       Enable detailed exit code output. (default false) 0 - pingcli command succeeded with no errors or warnings. 1 - pingcli command failed with errors. 2 - pingcli command succeeded with warnings.
  -O, --output-format string    Specify the console output format. (default text) Options are: json, ndjson, ndjson-wrapped, text.
  -P, --profile string          The name of a configuration profile to use.
      --debug                   Enable debug output for error messages, including stack traces and transaction IDs. (default false)
      --log-file string         Write logs to a file at the given path. File logging is disabled when not set.
      --log-file-level string   Set the file log level. Options are: DEBUG, INFO, WARN, ERROR. (default DEBUG)
      --log-level string        Set the console log level. Options are: DEBUG, INFO, WARN, ERROR. (default WARN)
      --no-color                Disable text output in color. (default false)
      --query string            JMESPath expression to filter JSON output. Requires -O json, ndjson, or ndjson-wrapped. Example: --query 'data[?enabled].name'
----

== More information

* xref:pingcli_authorize_application-roles.adoc[]	 - Application Roles

== Subcommands

* xref:pingcli_authorize_application-roles_app-role-permissions_create.adoc[] - Create a new application role permission
* xref:pingcli_authorize_application-roles_app-role-permissions_delete.adoc[] - Delete an application role permission
* xref:pingcli_authorize_application-roles_app-role-permissions_get.adoc[] - Read a specific application role permission
* xref:pingcli_authorize_application-roles_app-role-permissions_list.adoc[] - List all application role permissions
* xref:pingcli_authorize_application-roles_app-role-permissions_template.adoc[] - Generate an application role permission JSON template
