= pingcli pingone davinci applications
:created-date: May 28, 2026
:revdate: June 5, 2026
:resourceid: pingcli_command_reference_pingcli_pingone_davinci_applications

DaVinci Applications

== Synopsis

DaVinci Applications

----
pingcli pingone davinci applications [flags]
----

== Options inherited from parent commands

----
  -C, --config string           The relative or full path to a custom Ping CLI configuration file. (default $HOME/.pingcli/config.yaml)
  -D, --detailed-exitcode       Enable detailed exit code output. (default false) 0 - pingcli command succeeded with no errors or warnings. 1 - pingcli command failed with errors. 2 - pingcli command succeeded with warnings.
  -O, --output-format string    Specify the console output format. (default text) Options are: json, ndjson, ndjson-wrapped, text.
  -P, --profile string          The name of a configuration profile to use.
      --debug                   Enable debug output for error messages, including stack traces and transaction IDs. (default false)
      --log-file string         Write logs to a file at the given path. File logging is disabled when not set.
      --log-file-level string   Set the file log level. Options are: DEBUG, INFO, WARN, ERROR. (default DEBUG)
      --log-level string        Set the console log level. Options are: DEBUG, INFO, WARN, ERROR. (default WARN)
      --no-color                Disable text output in color. (default false)
      --query string            JMESPath expression to filter JSON output. Requires -O json, ndjson, or ndjson-wrapped. Example: --query 'data[?enabled].name'
----

== More information

* xref:pingcli_pingone_davinci.adoc[]	 - Administration tools for the PingOne DaVinci universal service.

== Subcommands

* xref:pingcli_pingone_davinci_applications_apply.adoc[] - Create or update a DaVinci application
* xref:pingcli_pingone_davinci_applications_create.adoc[] - Create a new DaVinci application
* xref:pingcli_pingone_davinci_applications_delete.adoc[] - Delete a DaVinci application
* xref:pingcli_pingone_davinci_applications_flow-policies.adoc[] - DaVinci Flow Policies
* xref:pingcli_pingone_davinci_applications_get.adoc[] - Read a DaVinci application
* xref:pingcli_pingone_davinci_applications_list.adoc[] - List DaVinci applications
* xref:pingcli_pingone_davinci_applications_replace.adoc[] - Update a DaVinci application
* xref:pingcli_pingone_davinci_applications_rotate-key.adoc[] - Rotate a DaVinci application API key
* xref:pingcli_pingone_davinci_applications_rotate-secret.adoc[] - Rotate a DaVinci application OAuth secret
* xref:pingcli_pingone_davinci_applications_template.adoc[] - Generate a DaVinci application JSON template
