= pingcli pingone
:created-date: March 3, 2026
:revdate: June 8, 2026
:resourceid: pingcli_command_reference_pingcli_pingone

Administration tools for the PingOne platform.

== Synopsis

Administration tools for the PingOne platform and universal services.
		
When multiple products are configured in the CLI, the platform command can be used to manage one or more products collectively.

The --profile command switch can be used to specify the profile of Ping products to be managed.

----
pingcli pingone
----

== Options inherited from parent commands

----
  -C, --config string           The relative or full path to a custom Ping CLI configuration file. (default $HOME/.pingcli/config.yaml)
  -D, --detailed-exitcode       Enable detailed exit code output. (default false) 0 - pingcli command succeeded with no errors or warnings. 1 - pingcli command failed with errors. 2 - pingcli command succeeded with warnings.
  -O, --output-format string    Specify the console output format. (default text) Options are: json, ndjson, ndjson-wrapped, text.
  -P, --profile string          The name of a configuration profile to use.
      --debug                   Enable debug output for error messages, including stack traces and transaction IDs. (default false)
      --log-file string         Write logs to a file at the given path. File logging is disabled when not set.
      --log-file-level string   Set the file log level. Options are: DEBUG, INFO, WARN, ERROR. (default DEBUG)
      --log-level string        Set the console log level. Options are: DEBUG, INFO, WARN, ERROR. (default WARN)
      --no-color                Disable text output in color. (default false)
      --query string            JMESPath expression to filter JSON output. Requires -O json, ndjson, or ndjson-wrapped. Example: --query 'data[?enabled].name'
----

== More information

* xref:pingcli.adoc[]	 - A CLI tool for managing the configuration of Ping Identity products.

== Subcommands

* xref:pingcli_pingone_agreements.adoc[] - Agreements
* xref:pingcli_pingone_api.adoc[] - Send a custom REST API request to the management API of PingOne.
* xref:pingcli_pingone_applications.adoc[] - Applications
* xref:pingcli_pingone_auth.adoc[] - Authenticate Ping CLI to the PingOne management APIs.
* xref:pingcli_pingone_authorize.adoc[] - Administration tools for the PingOne Authorize universal service.
* xref:pingcli_pingone_credentials.adoc[] - Administration tools for the PingOne Credentials universal service.
* xref:pingcli_pingone_davinci.adoc[] - Administration tools for the PingOne DaVinci universal service.
* xref:pingcli_pingone_environments.adoc[] - Environments
* xref:pingcli_pingone_gateways.adoc[] - Gateways
* xref:pingcli_pingone_groups.adoc[] - Groups
* xref:pingcli_pingone_identity-providers.adoc[] - Identity Providers
* xref:pingcli_pingone_init.adoc[] - Initialize Ping CLI for the PingOne management APIs.
* xref:pingcli_pingone_languages.adoc[] - Languages
* xref:pingcli_pingone_licenses.adoc[] - PingOne Licenses
* xref:pingcli_pingone_mfa.adoc[] - Administration tools for the PingOne MFA universal service.
* xref:pingcli_pingone_notification-policies.adoc[] - Notification Policies
* xref:pingcli_pingone_notification-templates.adoc[] - Notification Templates
* xref:pingcli_pingone_password-policies.adoc[] - Password Policies
* xref:pingcli_pingone_populations.adoc[] - Populations
* xref:pingcli_pingone_protect.adoc[] - Administration tools for the PingOne Protect universal service.
* xref:pingcli_pingone_resources.adoc[] - Resources
* xref:pingcli_pingone_roles.adoc[] - Roles
* xref:pingcli_pingone_schemas.adoc[] - Schemas
* xref:pingcli_pingone_sign-on-policies.adoc[] - Sign-On Policies
* xref:pingcli_pingone_total-identities.adoc[] - Total identity counts
* xref:pingcli_pingone_users.adoc[] - Users
* xref:pingcli_pingone_verify.adoc[] - Administration tools for the PingOne Verify universal service.
* xref:pingcli_pingone_webhooks.adoc[] - Webhooks
