= pingcli pingone protect risk-predictors
:created-date: June 5, 2026
:revdate: June 5, 2026
:resourceid: pingcli_command_reference_pingcli_pingone_protect_risk-predictors

Risk Predictors

== Synopsis

Risk Predictors

----
pingcli pingone protect risk-predictors [flags]
----

== Options inherited from parent commands

----
  -C, --config string           The relative or full path to a custom Ping CLI configuration file. (default $HOME/.pingcli/config.yaml)
  -D, --detailed-exitcode       Enable detailed exit code output. (default false) 0 - pingcli command succeeded with no errors or warnings. 1 - pingcli command failed with errors. 2 - pingcli command succeeded with warnings.
  -O, --output-format string    Specify the console output format. (default text) Options are: json, ndjson, ndjson-wrapped, text.
  -P, --profile string          The name of a configuration profile to use.
      --debug                   Enable debug output for error messages, including stack traces and transaction IDs. (default false)
      --log-file string         Write logs to a file at the given path. File logging is disabled when not set.
      --log-file-level string   Set the file log level. Options are: DEBUG, INFO, WARN, ERROR. (default DEBUG)
      --log-level string        Set the console log level. Options are: DEBUG, INFO, WARN, ERROR. (default WARN)
      --no-color                Disable text output in color. (default false)
      --query string            JMESPath expression to filter JSON output. Requires -O json, ndjson, or ndjson-wrapped. Example: --query 'data[?enabled].name'
----

== More information

* xref:pingcli_pingone_protect.adoc[]	 - Administration tools for the PingOne Protect universal service.

== Subcommands

* xref:pingcli_pingone_protect_risk-predictors_apply.adoc[] - Create or update a risk predictor
* xref:pingcli_pingone_protect_risk-predictors_create.adoc[] - Create a new risk predictor
* xref:pingcli_pingone_protect_risk-predictors_delete.adoc[] - Delete a risk predictor
* xref:pingcli_pingone_protect_risk-predictors_get.adoc[] - Read a specific risk predictor
* xref:pingcli_pingone_protect_risk-predictors_list.adoc[] - List all risk predictors
* xref:pingcli_pingone_protect_risk-predictors_replace.adoc[] - Replace a risk predictor
* xref:pingcli_pingone_protect_risk-predictors_template.adoc[] - Generate a risk predictor JSON template
