// Copyright © 2025 Ping Identity Corporation
// Code generated by ping-cli-generator

package resources

import (
	"fmt"

	"github.com/patrickcping/pingone-go-sdk-v2/authorize"
	"github.com/pingidentity/pingcli/internal/connector"
	"github.com/pingidentity/pingcli/internal/connector/common"
	"github.com/pingidentity/pingcli/internal/connector/pingone"
	"github.com/pingidentity/pingcli/internal/logger"
	"github.com/pingidentity/pingcli/internal/utils"
)

// Verify that the resource satisfies the exportable resource interface
var (
	_ connector.ExportableResource = &PingOneApplicationResourcePermissionResource{}
)

type PingOneApplicationResourcePermissionResource struct {
	clientInfo *connector.ClientInfo
}

// Utility method for creating a PingOneApplicationResourcePermissionResource
func ApplicationResourcePermission(clientInfo *connector.ClientInfo) *PingOneApplicationResourcePermissionResource {
	return &PingOneApplicationResourcePermissionResource{
		clientInfo: clientInfo,
	}
}

func (r *PingOneApplicationResourcePermissionResource) ResourceType() string {
	return "pingone_application_resource_permission"
}

func (r *PingOneApplicationResourcePermissionResource) ExportAll() (*[]connector.ImportBlock, error) {
	l := logger.Get()
	l.Debug().Msgf("Exporting all '%s' Resources...", r.ResourceType())

	importBlocks := []connector.ImportBlock{}

	applicationResourceData, err := r.getApplicationResourceData()
	if err != nil {
		return nil, err
	}

	for applicationResourceId, applicationResourceName := range applicationResourceData {
		applicationResourcePermissionData, err := r.getApplicationResourcePermissionData(applicationResourceId)
		if err != nil {
			return nil, err
		}

		for applicationResourcePermissionId, applicationResourcePermissionKey := range applicationResourcePermissionData {
			commentData := map[string]string{
				"Application Resource ID":             applicationResourceId,
				"Application Resource Name":           applicationResourceName,
				"Application Resource Permission ID":  applicationResourcePermissionId,
				"Application Resource Permission Key": applicationResourcePermissionKey,
				"Export Environment ID":               r.clientInfo.PingOneExportEnvironmentID,
				"Resource Type":                       r.ResourceType(),
			}

			importBlock := connector.ImportBlock{
				ResourceType:       r.ResourceType(),
				ResourceName:       fmt.Sprintf("%s_%s", applicationResourceName, applicationResourcePermissionKey),
				ResourceID:         fmt.Sprintf("%s/%s/%s", r.clientInfo.PingOneExportEnvironmentID, applicationResourceId, applicationResourcePermissionId),
				CommentInformation: common.GenerateCommentInformation(commentData),
			}

			importBlocks = append(importBlocks, importBlock)
		}
	}

	return &importBlocks, nil
}

func (r *PingOneApplicationResourcePermissionResource) getApplicationResourceData() (map[string]string, error) {
	applicationResourceData := make(map[string]string)

	iter := r.clientInfo.PingOneApiClient.AuthorizeAPIClient.ApplicationResourcesApi.ReadApplicationResources(r.clientInfo.PingOneContext, r.clientInfo.PingOneExportEnvironmentID).Execute()
	apiObjs, err := pingone.GetAuthorizeAPIObjectsFromIterator[authorize.ApplicationResource](iter, "ReadApplicationResources", "GetResources", r.ResourceType())
	if err != nil {
		return nil, err
	}

	for _, applicationResource := range apiObjs {
		applicationResourceId, applicationResourceIdOk := applicationResource.GetIdOk()
		applicationResourceName, applicationResourceNameOk := applicationResource.GetNameOk()

		if applicationResourceIdOk && applicationResourceNameOk {
			applicationResourceData[*applicationResourceId] = *applicationResourceName
		}
	}

	return applicationResourceData, nil
}

func (r *PingOneApplicationResourcePermissionResource) getApplicationResourcePermissionData(applicationResourceId string) (map[string]string, error) {
	applicationResourcePermissionData := make(map[string]string)

	iter := r.clientInfo.PingOneApiClient.AuthorizeAPIClient.ApplicationResourcePermissionsApi.ReadApplicationPermissions(r.clientInfo.PingOneContext, r.clientInfo.PingOneExportEnvironmentID, applicationResourceId).Execute()
	apiObjs, err := pingone.GetAuthorizeAPIObjectsFromIterator[authorize.EntityArrayEmbeddedPermissionsInner](iter, "ReadApplicationPermissions", "GetPermissions", r.ResourceType())
	if err != nil {
		return nil, err
	}

	for _, innerObj := range apiObjs {
		var (
			applicationResourcePermissionId   *string
			applicationResourcePermissionIdOk bool

			applicationResourcePermissionKey   *string
			applicationResourcePermissionKeyOk bool
		)

		switch {
		case innerObj.ApplicationResourcePermission != nil:
			applicationResourcePermissionId, applicationResourcePermissionIdOk = innerObj.ApplicationResourcePermission.GetIdOk()
			applicationResourcePermissionAction, applicationResourcePermissionActionOk := innerObj.ApplicationResourcePermission.GetActionOk()
			applicationResourcePermissionResource, applicationResourcePermissionResourceOk := innerObj.ApplicationResourcePermission.GetResourceOk()

			if applicationResourcePermissionIdOk && applicationResourcePermissionActionOk && applicationResourcePermissionResourceOk {
				applicationResourcePermissionResourceName, applicationResourcePermissionResourceNameOk := applicationResourcePermissionResource.GetNameOk()

				if applicationResourcePermissionResourceNameOk {
					applicationResourcePermissionKey, applicationResourcePermissionKeyOk = utils.Pointer(fmt.Sprintf("%s:%s", *applicationResourcePermissionResourceName, *applicationResourcePermissionAction)), true
				}
			}
		case innerObj.ApplicationRolePermission != nil:
			applicationResourcePermissionId, applicationResourcePermissionIdOk = innerObj.ApplicationRolePermission.GetIdOk()
			applicationResourcePermissionKey, applicationResourcePermissionKeyOk = innerObj.ApplicationRolePermission.GetKeyOk()
		}

		if applicationResourcePermissionIdOk && applicationResourcePermissionKeyOk {
			applicationResourcePermissionData[*applicationResourcePermissionId] = *applicationResourcePermissionKey
		}
	}

	return applicationResourcePermissionData, nil
}
