// Copyright © 2025 Ping Identity Corporation
// Code generated by ping-cli-generator

package resources

import (
	"fmt"

	"github.com/patrickcping/pingone-go-sdk-v2/authorize"
	"github.com/pingidentity/pingcli/internal/connector"
	"github.com/pingidentity/pingcli/internal/connector/common"
	"github.com/pingidentity/pingcli/internal/connector/pingone"
	"github.com/pingidentity/pingcli/internal/logger"
)

// Verify that the resource satisfies the exportable resource interface
var (
	_ connector.ExportableResource = &PingOneAuthorizeApplicationRoleResource{}
)

type PingOneAuthorizeApplicationRoleResource struct {
	clientInfo *connector.ClientInfo
}

// Utility method for creating a PingOneAuthorizeApplicationRoleResource
func AuthorizeApplicationRole(clientInfo *connector.ClientInfo) *PingOneAuthorizeApplicationRoleResource {
	return &PingOneAuthorizeApplicationRoleResource{
		clientInfo: clientInfo,
	}
}

func (r *PingOneAuthorizeApplicationRoleResource) ResourceType() string {
	return "pingone_authorize_application_role"
}

func (r *PingOneAuthorizeApplicationRoleResource) ExportAll() (*[]connector.ImportBlock, error) {
	l := logger.Get()
	l.Debug().Msgf("Exporting all '%s' Resources...", r.ResourceType())

	importBlocks := []connector.ImportBlock{}

	authorizeApplicationRoleData, err := r.getAuthorizeApplicationRoleData()
	if err != nil {
		return nil, err
	}

	for authorizeApplicationRoleId, authorizeApplicationRoleName := range authorizeApplicationRoleData {
		commentData := map[string]string{
			"Authorize Application Role ID":   authorizeApplicationRoleId,
			"Authorize Application Role Name": authorizeApplicationRoleName,
			"Export Environment ID":           r.clientInfo.PingOneExportEnvironmentID,
			"Resource Type":                   r.ResourceType(),
		}

		importBlock := connector.ImportBlock{
			ResourceType:       r.ResourceType(),
			ResourceName:       authorizeApplicationRoleName,
			ResourceID:         fmt.Sprintf("%s/%s", r.clientInfo.PingOneExportEnvironmentID, authorizeApplicationRoleId),
			CommentInformation: common.GenerateCommentInformation(commentData),
		}

		importBlocks = append(importBlocks, importBlock)
	}

	return &importBlocks, nil
}

func (r *PingOneAuthorizeApplicationRoleResource) getAuthorizeApplicationRoleData() (map[string]string, error) {
	authorizeApplicationRoleData := make(map[string]string)

	iter := r.clientInfo.PingOneApiClient.AuthorizeAPIClient.ApplicationRolesApi.ReadApplicationRoles(r.clientInfo.PingOneContext, r.clientInfo.PingOneExportEnvironmentID).Execute()
	apiObjs, err := pingone.GetAuthorizeAPIObjectsFromIterator[authorize.ApplicationRole](iter, "ReadApplicationRoles", "GetRoles", r.ResourceType())
	if err != nil {
		return nil, err
	}

	for _, authorizeApplicationRole := range apiObjs {
		authorizeApplicationRoleId, authorizeApplicationRoleIdOk := authorizeApplicationRole.GetIdOk()
		authorizeApplicationRoleName, authorizeApplicationRoleNameOk := authorizeApplicationRole.GetNameOk()

		if authorizeApplicationRoleIdOk && authorizeApplicationRoleNameOk {
			authorizeApplicationRoleData[*authorizeApplicationRoleId] = *authorizeApplicationRoleName
		}
	}

	return authorizeApplicationRoleData, nil
}
