// Copyright © 2025 Ping Identity Corporation
// Code generated by ping-cli-generator

package pingone_sso_testable_resources

import (
	"testing"

	"github.com/hashicorp/go-uuid"
	"github.com/patrickcping/pingone-go-sdk-v2/management"
	"github.com/pingidentity/pingcli/internal/connector"
	"github.com/pingidentity/pingcli/internal/connector/common"
	"github.com/pingidentity/pingcli/internal/connector/pingone/sso/resources"
	"github.com/pingidentity/pingcli/internal/testing/testutils_resource"
	"github.com/pingidentity/pingcli/internal/utils"
)

func ApplicationNative(t *testing.T, clientInfo *connector.ClientInfo) *testutils_resource.TestableResource {
	t.Helper()

	return &testutils_resource.TestableResource{
		ClientInfo:         clientInfo,
		CreateFunc:         createApplicationNative,
		DeleteFunc:         deleteApplicationNative,
		Dependencies:       nil,
		ExportableResource: resources.Application(clientInfo),
	}
}

func createApplicationNative(t *testing.T, clientInfo *connector.ClientInfo, resourceType string, strArgs ...string) testutils_resource.ResourceInfo {
	t.Helper()

	if len(strArgs) != 0 {
		t.Errorf("Unexpected number of arguments provided to createApplicationNative(): %v", strArgs)

		return testutils_resource.ResourceInfo{}
	}

	// Give unique name to application to avoid collisions in dependency creations
	applicationName, err := uuid.GenerateUUID()
	if err != nil {
		t.Errorf("Failed to generate UUID for application name: %v", err)

		return testutils_resource.ResourceInfo{}
	}

	request := clientInfo.PingOneApiClient.ManagementAPIClient.ApplicationsApi.CreateApplication(clientInfo.PingOneContext, clientInfo.PingOneExportEnvironmentID)
	clientStruct := management.CreateApplicationRequest{
		ApplicationOIDC: &management.ApplicationOIDC{
			Enabled:      true,
			Name:         applicationName,
			Description:  utils.Pointer("Test Native OIDC Application"),
			Type:         management.ENUMAPPLICATIONTYPE_NATIVE_APP,
			Protocol:     management.ENUMAPPLICATIONPROTOCOL_OPENID_CONNECT,
			HomePageUrl:  utils.Pointer("https://example.com/homePage"),
			LoginPageUrl: utils.Pointer("https://example.com/loginPage"),
			GrantTypes: []management.EnumApplicationOIDCGrantType{
				management.ENUMAPPLICATIONOIDCGRANTTYPE_AUTHORIZATION_CODE,
				management.ENUMAPPLICATIONOIDCGRANTTYPE_IMPLICIT,
			},
			PostLogoutRedirectUris: []string{
				"https://example.com/logout",
			},
			RedirectUris: []string{
				"https://example.com",
			},
			ResponseTypes: []management.EnumApplicationOIDCResponseType{
				management.ENUMAPPLICATIONOIDCRESPONSETYPE_CODE,
				management.ENUMAPPLICATIONOIDCRESPONSETYPE_TOKEN,
				management.ENUMAPPLICATIONOIDCRESPONSETYPE_ID_TOKEN,
			},
			TokenEndpointAuthMethod:     management.ENUMAPPLICATIONOIDCTOKENAUTHMETHOD_NONE,
			PkceEnforcement:             utils.Pointer(management.ENUMAPPLICATIONOIDCPKCEOPTION_REQUIRED),
			RefreshTokenDuration:        utils.Pointer(int32(86400)),
			RefreshTokenRollingDuration: utils.Pointer(int32(86400)),
		},
	}

	request = request.CreateApplicationRequest(clientStruct)

	resource, response, err := request.Execute()
	ok, err := common.HandleClientResponse(response, err, "CreateApplication", resourceType)
	if err != nil {
		t.Errorf("Failed to execute PingOne client function\nResponse Status: %s\nResponse Body: %s\nError: %v", response.Status, response.Body, err)

		return testutils_resource.ResourceInfo{}
	}
	if !ok {
		t.Errorf("Failed to execute PingOne client function\nResponse Status: %s\nResponse Body: %s", response.Status, response.Body)

		return testutils_resource.ResourceInfo{}
	}

	return testutils_resource.ResourceInfo{
		DeletionIds: []string{
			*resource.ApplicationOIDC.Id,
		},
		CreationInfo: map[testutils_resource.ResourceCreationInfoType]string{
			testutils_resource.ENUM_ID:   *resource.ApplicationOIDC.Id,
			testutils_resource.ENUM_NAME: resource.ApplicationOIDC.Name,
		},
	}
}

func deleteApplicationNative(t *testing.T, clientInfo *connector.ClientInfo, resourceType string, ids ...string) {
	t.Helper()

	if len(ids) != 1 {
		t.Errorf("Unexpected number of arguments provided to deleteApplicationNative(): %v", ids)

		return
	}

	request := clientInfo.PingOneApiClient.ManagementAPIClient.ApplicationsApi.DeleteApplication(clientInfo.PingOneContext, clientInfo.PingOneExportEnvironmentID, ids[0])

	response, err := request.Execute()
	ok, err := common.HandleClientResponse(response, err, "DeleteApplication", resourceType)
	if err != nil {
		t.Errorf("Failed to execute PingOne client function\nResponse Status: %s\nResponse Body: %s\nError: %v", response.Status, response.Body, err)

		return
	}
	if !ok {
		t.Errorf("Failed to execute PingOne client function\nResponse Status: %s\nResponse Body: %s", response.Status, response.Body)

		return
	}
}
