// Copyright © 2025 Ping Identity Corporation
// Code generated by ping-cli-generator

package pingone_sso_testable_resources

import (
	"testing"

	"github.com/patrickcping/pingone-go-sdk-v2/management"
	"github.com/pingidentity/pingcli/internal/connector"
	"github.com/pingidentity/pingcli/internal/connector/common"
	"github.com/pingidentity/pingcli/internal/connector/pingone/sso/resources"
	"github.com/pingidentity/pingcli/internal/testing/testutils_resource"
)

func GroupNesting(t *testing.T, clientInfo *connector.ClientInfo) *testutils_resource.TestableResource {
	t.Helper()

	return &testutils_resource.TestableResource{
		ClientInfo: clientInfo,
		CreateFunc: createGroupNesting,
		DeleteFunc: deleteGroupNesting,
		Dependencies: []*testutils_resource.TestableResource{
			Group(t, clientInfo),
			Group(t, clientInfo),
		},
		ExportableResource: resources.GroupNesting(clientInfo),
	}
}

func createGroupNesting(t *testing.T, clientInfo *connector.ClientInfo, resourceType string, strArgs ...string) testutils_resource.ResourceInfo {
	t.Helper()

	if len(strArgs) != 2 {
		t.Errorf("Unexpected number of arguments provided to createGroupNesting(): %v", strArgs)

		return testutils_resource.ResourceInfo{}
	}
	groupId := strArgs[0]
	nestedGroupId := strArgs[1]

	request := clientInfo.PingOneApiClient.ManagementAPIClient.GroupsApi.CreateGroupNesting(clientInfo.PingOneContext, clientInfo.PingOneExportEnvironmentID, groupId)
	clientStruct := management.GroupNesting{
		Id: nestedGroupId,
	}

	request = request.GroupNesting(clientStruct)

	resource, response, err := request.Execute()
	ok, err := common.HandleClientResponse(response, err, "CreateGroupNesting", resourceType)
	if err != nil {
		t.Errorf("Failed to execute PingOne client function\nResponse Status: %s\nResponse Body: %s\nError: %v", response.Status, response.Body, err)

		return testutils_resource.ResourceInfo{}
	}
	if !ok {
		t.Errorf("Failed to execute PingOne client function\nResponse Status: %s\nResponse Body: %s", response.Status, response.Body)

		return testutils_resource.ResourceInfo{}
	}

	group, response, err := clientInfo.PingOneApiClient.ManagementAPIClient.GroupsApi.ReadOneGroup(clientInfo.PingOneContext, clientInfo.PingOneExportEnvironmentID, groupId).Execute()
	ok, err = common.HandleClientResponse(response, err, "ReadOneGroup", resourceType)
	if err != nil {
		t.Errorf("Failed to execute PingOne client function\nResponse Status: %s\nResponse Body: %s\nError: %v", response.Status, response.Body, err)

		return testutils_resource.ResourceInfo{}
	}
	if !ok {
		t.Errorf("Failed to execute PingOne client function\nResponse Status: %s\nResponse Body: %s", response.Status, response.Body)

		return testutils_resource.ResourceInfo{}
	}

	return testutils_resource.ResourceInfo{
		DeletionIds: []string{
			groupId,
			nestedGroupId,
		},
		CreationInfo: map[testutils_resource.ResourceCreationInfoType]string{
			testutils_resource.ENUM_ID:   resource.Id,
			testutils_resource.ENUM_NAME: group.Name,
		},
	}
}

func deleteGroupNesting(t *testing.T, clientInfo *connector.ClientInfo, resourceType string, ids ...string) {
	t.Helper()

	if len(ids) != 2 {
		t.Errorf("Unexpected number of arguments provided to deleteGroupNesting(): %v", ids)

		return
	}

	request := clientInfo.PingOneApiClient.ManagementAPIClient.GroupsApi.DeleteGroupNesting(clientInfo.PingOneContext, clientInfo.PingOneExportEnvironmentID, ids[0], ids[1])

	response, err := request.Execute()
	ok, err := common.HandleClientResponse(response, err, "DeleteGroupNesting", resourceType)
	if err != nil {
		t.Errorf("Failed to execute PingOne client function\nResponse Status: %s\nResponse Body: %s\nError: %v", response.Status, response.Body, err)

		return
	}
	if !ok {
		t.Errorf("Failed to execute PingOne client function\nResponse Status: %s\nResponse Body: %s", response.Status, response.Body)

		return
	}
}
