// Copyright © 2025 Ping Identity Corporation
// Code generated by ping-cli-generator

package pingone_sso_testable_resources

import (
	"testing"

	"github.com/patrickcping/pingone-go-sdk-v2/management"
	"github.com/pingidentity/pingcli/internal/connector"
	"github.com/pingidentity/pingcli/internal/connector/common"
	"github.com/pingidentity/pingcli/internal/connector/pingone/sso/resources"
	"github.com/pingidentity/pingcli/internal/testing/testutils_resource"
)

func IdentityProviderAttribute(t *testing.T, clientInfo *connector.ClientInfo) *testutils_resource.TestableResource {
	t.Helper()

	return &testutils_resource.TestableResource{
		ClientInfo: clientInfo,
		CreateFunc: createIdentityProviderAttribute,
		DeleteFunc: deleteIdentityProviderAttribute,
		Dependencies: []*testutils_resource.TestableResource{
			IdentityProvider(t, clientInfo),
		},
		ExportableResource: resources.IdentityProviderAttribute(clientInfo),
	}
}

func createIdentityProviderAttribute(t *testing.T, clientInfo *connector.ClientInfo, resourceType string, strArgs ...string) testutils_resource.ResourceInfo {
	t.Helper()

	if len(strArgs) != 1 {
		t.Errorf("Unexpected number of arguments provided to createIdentityProviderAttribute(): %v", strArgs)

		return testutils_resource.ResourceInfo{}
	}

	providerId := strArgs[0]

	request := clientInfo.PingOneApiClient.ManagementAPIClient.IdentityProviderAttributesApi.CreateIdentityProviderAttribute(clientInfo.PingOneContext, clientInfo.PingOneExportEnvironmentID, providerId)
	clientStruct := management.IdentityProviderAttribute{
		Name:   "email",
		Update: management.ENUMIDENTITYPROVIDERATTRIBUTEMAPPINGUPDATE_EMPTY_ONLY,
		Value:  "${providerAttributes.user.emailAddress}",
	}

	request = request.IdentityProviderAttribute(clientStruct)

	resource, response, err := request.Execute()
	ok, err := common.HandleClientResponse(response, err, "CreateIdentityProviderAttribute", resourceType)
	if err != nil {
		t.Errorf("Failed to execute PingOne client function\nResponse Status: %s\nResponse Body: %s\nError: %v", response.Status, response.Body, err)

		return testutils_resource.ResourceInfo{}
	}
	if !ok {
		t.Errorf("Failed to execute PingOne client function\nResponse Status: %s\nResponse Body: %s", response.Status, response.Body)

		return testutils_resource.ResourceInfo{}
	}

	return testutils_resource.ResourceInfo{
		DeletionIds: []string{
			providerId,
			*resource.Id,
		},
		CreationInfo: map[testutils_resource.ResourceCreationInfoType]string{
			testutils_resource.ENUM_ID:   *resource.Id,
			testutils_resource.ENUM_NAME: resource.Name,
		},
	}
}

func deleteIdentityProviderAttribute(t *testing.T, clientInfo *connector.ClientInfo, resourceType string, ids ...string) {
	t.Helper()

	if len(ids) != 2 {
		t.Errorf("Unexpected number of arguments provided to deleteIdentityProviderAttribute(): %v", ids)

		return
	}

	request := clientInfo.PingOneApiClient.ManagementAPIClient.IdentityProviderAttributesApi.DeleteIdentityProviderAttribute(clientInfo.PingOneContext, clientInfo.PingOneExportEnvironmentID, ids[0], ids[1])

	response, err := request.Execute()
	ok, err := common.HandleClientResponse(response, err, "DeleteIdentityProviderAttribute", resourceType)
	if err != nil {
		t.Errorf("Failed to execute PingOne client function\nResponse Status: %s\nResponse Body: %s\nError: %v", response.Status, response.Body, err)

		return
	}
	if !ok {
		t.Errorf("Failed to execute PingOne client function\nResponse Status: %s\nResponse Body: %s", response.Status, response.Body)

		return
	}
}
