// Copyright © 2025 Ping Identity Corporation
// Code generated by ping-cli-generator

package pingone_sso_testable_resources

import (
	"testing"

	"github.com/patrickcping/pingone-go-sdk-v2/management"
	"github.com/pingidentity/pingcli/internal/connector"
	"github.com/pingidentity/pingcli/internal/connector/common"
	"github.com/pingidentity/pingcli/internal/connector/pingone/sso/resources"
	"github.com/pingidentity/pingcli/internal/testing/testutils_resource"
	"github.com/pingidentity/pingcli/internal/utils"
)

func PasswordPolicy(t *testing.T, clientInfo *connector.ClientInfo) *testutils_resource.TestableResource {
	t.Helper()

	return &testutils_resource.TestableResource{
		ClientInfo:         clientInfo,
		CreateFunc:         createPasswordPolicy,
		DeleteFunc:         deletePasswordPolicy,
		Dependencies:       nil,
		ExportableResource: resources.PasswordPolicy(clientInfo),
	}
}

func createPasswordPolicy(t *testing.T, clientInfo *connector.ClientInfo, resourceType string, strArgs ...string) testutils_resource.ResourceInfo {
	t.Helper()

	if len(strArgs) != 0 {
		t.Errorf("Unexpected number of arguments provided to createPasswordPolicy(): %v", strArgs)

		return testutils_resource.ResourceInfo{}
	}

	request := clientInfo.PingOneApiClient.ManagementAPIClient.PasswordPoliciesApi.CreatePasswordPolicy(clientInfo.PingOneContext, clientInfo.PingOneExportEnvironmentID)
	clientStruct := management.PasswordPolicy{
		Name:                 "PassphraseCustom1",
		Description:          utils.Pointer("A policy that encourages the use of passphrases"),
		ExcludesProfileData:  true,
		NotSimilarToCurrent:  true,
		ExcludesCommonlyUsed: true,
		MinComplexity:        utils.Pointer(int32(7)),
		MaxAgeDays:           utils.Pointer(int32(182)),
		MinAgeDays:           utils.Pointer(int32(1)),
		History: &management.PasswordPolicyHistory{
			Count:         utils.Pointer(int32(8)),
			RetentionDays: utils.Pointer(int32(365)),
		},
		Lockout: &management.PasswordPolicyLockout{
			FailureCount:    utils.Pointer(int32(3)),
			DurationSeconds: utils.Pointer(int32(900)),
		},
		Default: utils.Pointer(false),
	}

	request = request.PasswordPolicy(clientStruct)

	resource, response, err := request.Execute()
	ok, err := common.HandleClientResponse(response, err, "CreatePasswordPolicy", resourceType)
	if err != nil {
		t.Errorf("Failed to execute PingOne client function\nResponse Status: %s\nResponse Body: %s\nError: %v", response.Status, response.Body, err)

		return testutils_resource.ResourceInfo{}
	}
	if !ok {
		t.Errorf("Failed to execute PingOne client function\nResponse Status: %s\nResponse Body: %s", response.Status, response.Body)

		return testutils_resource.ResourceInfo{}
	}

	return testutils_resource.ResourceInfo{
		DeletionIds: []string{
			*resource.Id,
		},
		CreationInfo: map[testutils_resource.ResourceCreationInfoType]string{
			testutils_resource.ENUM_ID:   *resource.Id,
			testutils_resource.ENUM_NAME: resource.Name,
		},
	}
}

func deletePasswordPolicy(t *testing.T, clientInfo *connector.ClientInfo, resourceType string, ids ...string) {
	t.Helper()

	if len(ids) != 1 {
		t.Errorf("Unexpected number of arguments provided to deletePasswordPolicy(): %v", ids)

		return
	}

	request := clientInfo.PingOneApiClient.ManagementAPIClient.PasswordPoliciesApi.DeletePasswordPolicy(clientInfo.PingOneContext, clientInfo.PingOneExportEnvironmentID, ids[0])

	response, err := request.Execute()
	ok, err := common.HandleClientResponse(response, err, "DeletePasswordPolicy", resourceType)
	if err != nil {
		t.Errorf("Failed to execute PingOne client function\nResponse Status: %s\nResponse Body: %s\nError: %v", response.Status, response.Body, err)

		return
	}
	if !ok {
		t.Errorf("Failed to execute PingOne client function\nResponse Status: %s\nResponse Body: %s", response.Status, response.Body)

		return
	}
}
