// Copyright © 2025 Ping Identity Corporation
// Code generated by ping-cli-generator

package resources_test

import (
	"testing"

	"github.com/pingidentity/pingcli/internal/connector"
	"github.com/pingidentity/pingcli/internal/connector/pingfederate/resources"
	"github.com/pingidentity/pingcli/internal/testing/testutils"
	"github.com/pingidentity/pingcli/internal/testing/testutils_resource/pingfederate_testable_resources"
)

func Test_PingFederateClusterSettings(t *testing.T) {
	clientInfo := testutils.GetClientInfo(t)

	tr := pingfederate_testable_resources.ClusterSettings(t, clientInfo)
	resource, ok := tr.ExportableResource.(*resources.PingFederateClusterSettingsResource)
	if !ok {
		t.Fatalf("Error casting resource to PingFederateClusterSettingsResource")
	}

	valid, err := resource.ValidPingFederateVersion()
	if err != nil {
		t.Errorf("Error checking version compatibility: %v", err)
	}
	if !valid {
		t.Skipf("'%s' Resource is not supported in the version of PingFederate used. Skipping export test.", resource.ResourceType())
	}

	expectedImportBlocks := []connector.ImportBlock{
		{
			ResourceType: tr.ExportableResource.ResourceType(),
			ResourceName: "Cluster Settings",
			ResourceID:   "cluster_settings_singleton_id",
		},
	}

	testutils.ValidateImportBlocks(t, tr.ExportableResource, &expectedImportBlocks)
}
