// Copyright © 2025 Ping Identity Corporation
// Code generated by ping-cli-generator

package resources

import (
	"fmt"

	"github.com/patrickcping/pingone-go-sdk-v2/management"
	"github.com/pingidentity/pingcli/internal/connector"
	"github.com/pingidentity/pingcli/internal/connector/common"
	"github.com/pingidentity/pingcli/internal/connector/pingone"
	"github.com/pingidentity/pingcli/internal/logger"
)

// Verify that the resource satisfies the exportable resource interface
var (
	_ connector.ExportableResource = &PingOneCustomDomainResource{}
)

type PingOneCustomDomainResource struct {
	clientInfo *connector.ClientInfo
}

// Utility method for creating a PingOneCustomDomainResource
func CustomDomain(clientInfo *connector.ClientInfo) *PingOneCustomDomainResource {
	return &PingOneCustomDomainResource{
		clientInfo: clientInfo,
	}
}

func (r *PingOneCustomDomainResource) ResourceType() string {
	return "pingone_custom_domain"
}

func (r *PingOneCustomDomainResource) ExportAll() (*[]connector.ImportBlock, error) {
	l := logger.Get()
	l.Debug().Msgf("Exporting all '%s' Resources...", r.ResourceType())

	importBlocks := []connector.ImportBlock{}

	customDomainData, err := r.getCustomDomainData()
	if err != nil {
		return nil, err
	}

	for customDomainId, customDomainName := range customDomainData {
		commentData := map[string]string{
			"Custom Domain ID":      customDomainId,
			"Custom Domain Name":    customDomainName,
			"Export Environment ID": r.clientInfo.PingOneExportEnvironmentID,
			"Resource Type":         r.ResourceType(),
		}

		importBlock := connector.ImportBlock{
			ResourceType:       r.ResourceType(),
			ResourceName:       customDomainName,
			ResourceID:         fmt.Sprintf("%s/%s", r.clientInfo.PingOneExportEnvironmentID, customDomainId),
			CommentInformation: common.GenerateCommentInformation(commentData),
		}

		importBlocks = append(importBlocks, importBlock)
	}

	return &importBlocks, nil
}

func (r *PingOneCustomDomainResource) getCustomDomainData() (map[string]string, error) {
	customDomainData := make(map[string]string)

	iter := r.clientInfo.PingOneApiClient.ManagementAPIClient.CustomDomainsApi.ReadAllDomains(r.clientInfo.PingOneContext, r.clientInfo.PingOneExportEnvironmentID).Execute()
	apiObjs, err := pingone.GetManagementAPIObjectsFromIterator[management.CustomDomain](iter, "ReadAllDomains", "GetCustomDomains", r.ResourceType())
	if err != nil {
		return nil, err
	}

	for _, customDomain := range apiObjs {
		customDomainId, customDomainIdOk := customDomain.GetIdOk()
		customDomainName, customDomainNameOk := customDomain.GetDomainNameOk()

		if customDomainIdOk && customDomainNameOk {
			customDomainData[*customDomainId] = *customDomainName
		}
	}

	return customDomainData, nil
}
