// Copyright © 2025 Ping Identity Corporation
// Code generated by ping-cli-generator

package resources

import (
	"fmt"

	"github.com/patrickcping/pingone-go-sdk-v2/management"
	"github.com/pingidentity/pingcli/internal/connector"
	"github.com/pingidentity/pingcli/internal/connector/common"
	"github.com/pingidentity/pingcli/internal/connector/pingone"
	"github.com/pingidentity/pingcli/internal/logger"
)

// Verify that the resource satisfies the exportable resource interface
var (
	_ connector.ExportableResource = &PingOneGatewayCredentialResource{}
)

type PingOneGatewayCredentialResource struct {
	clientInfo *connector.ClientInfo
}

// Utility method for creating a PingOneGatewayCredentialResource
func GatewayCredential(clientInfo *connector.ClientInfo) *PingOneGatewayCredentialResource {
	return &PingOneGatewayCredentialResource{
		clientInfo: clientInfo,
	}
}

func (r *PingOneGatewayCredentialResource) ResourceType() string {
	return "pingone_gateway_credential"
}

func (r *PingOneGatewayCredentialResource) ExportAll() (*[]connector.ImportBlock, error) {
	l := logger.Get()
	l.Debug().Msgf("Exporting all '%s' Resources...", r.ResourceType())

	importBlocks := []connector.ImportBlock{}

	gatewayData, err := r.getGatewayData()
	if err != nil {
		return nil, err
	}

	for gatewayId, gatewayName := range gatewayData {
		gatewayCredentialData, err := r.getGatewayCredentialData(gatewayId)
		if err != nil {
			return nil, err
		}

		for _, gatewayCredentialId := range gatewayCredentialData {
			commentData := map[string]string{
				"Gateway ID":            gatewayId,
				"Gateway Name":          gatewayName,
				"Gateway Credential ID": gatewayCredentialId,
				"Export Environment ID": r.clientInfo.PingOneExportEnvironmentID,
				"Resource Type":         r.ResourceType(),
			}

			importBlock := connector.ImportBlock{
				ResourceType:       r.ResourceType(),
				ResourceName:       fmt.Sprintf("%s_credential_%s", gatewayName, gatewayCredentialId),
				ResourceID:         fmt.Sprintf("%s/%s/%s", r.clientInfo.PingOneExportEnvironmentID, gatewayId, gatewayCredentialId),
				CommentInformation: common.GenerateCommentInformation(commentData),
			}

			importBlocks = append(importBlocks, importBlock)
		}
	}

	return &importBlocks, nil
}

func (r *PingOneGatewayCredentialResource) getGatewayData() (map[string]string, error) {
	gatewayData := make(map[string]string)

	iter := r.clientInfo.PingOneApiClient.ManagementAPIClient.GatewaysApi.ReadAllGateways(r.clientInfo.PingOneContext, r.clientInfo.PingOneExportEnvironmentID).Execute()
	apiObjs, err := pingone.GetManagementAPIObjectsFromIterator[management.EntityArrayEmbeddedGatewaysInner](iter, "ReadAllGateways", "GetGateways", r.ResourceType())
	if err != nil {
		return nil, err
	}

	for _, innerObj := range apiObjs {
		var (
			gatewayId     *string
			gatewayIdOk   bool
			gatewayName   *string
			gatewayNameOk bool
		)

		switch {
		case innerObj.Gateway != nil:
			gatewayId, gatewayIdOk = innerObj.Gateway.GetIdOk()
			gatewayName, gatewayNameOk = innerObj.Gateway.GetNameOk()
		case innerObj.GatewayTypeLDAP != nil:
			gatewayId, gatewayIdOk = innerObj.GatewayTypeLDAP.GetIdOk()
			gatewayName, gatewayNameOk = innerObj.GatewayTypeLDAP.GetNameOk()
		case innerObj.GatewayTypeRADIUS != nil:
			gatewayId, gatewayIdOk = innerObj.GatewayTypeRADIUS.GetIdOk()
			gatewayName, gatewayNameOk = innerObj.GatewayTypeRADIUS.GetNameOk()
		default:
			continue
		}

		if gatewayIdOk && gatewayNameOk {
			gatewayData[*gatewayId] = *gatewayName
		}
	}

	return gatewayData, nil
}

func (r *PingOneGatewayCredentialResource) getGatewayCredentialData(gatewayId string) ([]string, error) {
	gatewayCredentialData := []string{}

	iter := r.clientInfo.PingOneApiClient.ManagementAPIClient.GatewayCredentialsApi.ReadAllGatewayCredentials(r.clientInfo.PingOneContext, r.clientInfo.PingOneExportEnvironmentID, gatewayId).Execute()
	apiObjs, err := pingone.GetManagementAPIObjectsFromIterator[management.GatewayCredential](iter, "ReadAllGatewayCredentials", "GetCredentials", r.ResourceType())
	if err != nil {
		return nil, err
	}

	for _, gatewayCredential := range apiObjs {
		gatewayCredentialId, gatewayCredentialIdOk := gatewayCredential.GetIdOk()

		if gatewayCredentialIdOk {
			gatewayCredentialData = append(gatewayCredentialData, *gatewayCredentialId)
		}
	}

	return gatewayCredentialData, nil
}
