// Copyright © 2025 Ping Identity Corporation
// Code generated by ping-cli-generator

package resources

import (
	"fmt"

	"github.com/patrickcping/pingone-go-sdk-v2/management"
	"github.com/pingidentity/pingcli/internal/connector"
	"github.com/pingidentity/pingcli/internal/connector/common"
	"github.com/pingidentity/pingcli/internal/connector/pingone"
	"github.com/pingidentity/pingcli/internal/logger"
)

// Verify that the resource satisfies the exportable resource interface
var (
	_ connector.ExportableResource = &PingOneTrustedEmailAddressResource{}
)

type PingOneTrustedEmailAddressResource struct {
	clientInfo *connector.ClientInfo
}

// Utility method for creating a PingOneTrustedEmailAddressResource
func TrustedEmailAddress(clientInfo *connector.ClientInfo) *PingOneTrustedEmailAddressResource {
	return &PingOneTrustedEmailAddressResource{
		clientInfo: clientInfo,
	}
}

func (r *PingOneTrustedEmailAddressResource) ResourceType() string {
	return "pingone_trusted_email_address"
}

func (r *PingOneTrustedEmailAddressResource) ExportAll() (*[]connector.ImportBlock, error) {
	l := logger.Get()
	l.Debug().Msgf("Exporting all '%s' Resources...", r.ResourceType())

	importBlocks := []connector.ImportBlock{}

	trustedEmailDomainData, err := r.getEmailDomainData()
	if err != nil {
		return nil, err
	}

	for trustedEmailDomainId, trustedEmailDomainName := range trustedEmailDomainData {
		trustedEmailAddressData, err := r.getTrustedEmailAddressData(trustedEmailDomainId)
		if err != nil {
			return nil, err
		}

		for trustedEmailAddressId, trustedEmailAddress := range trustedEmailAddressData {
			commentData := map[string]string{
				"Trusted Email Domain ID":   trustedEmailDomainId,
				"Trusted Email Domain Name": trustedEmailDomainName,
				"Trusted Email Address ID":  trustedEmailAddressId,
				"Trusted Email Address":     trustedEmailAddress,
				"Export Environment ID":     r.clientInfo.PingOneExportEnvironmentID,
				"Resource Type":             r.ResourceType(),
			}

			importBlock := connector.ImportBlock{
				ResourceType:       r.ResourceType(),
				ResourceName:       fmt.Sprintf("%s_%s", trustedEmailDomainName, trustedEmailAddress),
				ResourceID:         fmt.Sprintf("%s/%s/%s", r.clientInfo.PingOneExportEnvironmentID, trustedEmailDomainId, trustedEmailAddressId),
				CommentInformation: common.GenerateCommentInformation(commentData),
			}

			importBlocks = append(importBlocks, importBlock)
		}
	}

	return &importBlocks, nil
}

func (r *PingOneTrustedEmailAddressResource) getEmailDomainData() (map[string]string, error) {
	trustedEmailDomainData := make(map[string]string)

	iter := r.clientInfo.PingOneApiClient.ManagementAPIClient.TrustedEmailDomainsApi.ReadAllTrustedEmailDomains(r.clientInfo.PingOneContext, r.clientInfo.PingOneExportEnvironmentID).Execute()
	apiObjs, err := pingone.GetManagementAPIObjectsFromIterator[management.EmailDomain](iter, "ReadAllTrustedEmailDomains", "GetEmailDomains", r.ResourceType())
	if err != nil {
		return nil, err
	}

	for _, trustedEmailDomain := range apiObjs {
		trustedEmailDomainId, trustedEmailDomainIdOk := trustedEmailDomain.GetIdOk()
		trustedEmailDomainName, trustedEmailDomainNameOk := trustedEmailDomain.GetDomainNameOk()

		if trustedEmailDomainIdOk && trustedEmailDomainNameOk {
			trustedEmailDomainData[*trustedEmailDomainId] = *trustedEmailDomainName
		}
	}

	return trustedEmailDomainData, nil
}

func (r *PingOneTrustedEmailAddressResource) getTrustedEmailAddressData(trustedEmailDomainId string) (map[string]string, error) {
	trustedEmailAddressData := make(map[string]string)

	iter := r.clientInfo.PingOneApiClient.ManagementAPIClient.TrustedEmailAddressesApi.ReadAllTrustedEmailAddresses(r.clientInfo.PingOneContext, r.clientInfo.PingOneExportEnvironmentID, trustedEmailDomainId).Execute()
	apiObjs, err := pingone.GetManagementAPIObjectsFromIterator[management.EmailDomainTrustedEmail](iter, "ReadAllTrustedEmailAddresses", "GetTrustedEmails", r.ResourceType())
	if err != nil {
		return nil, err
	}

	for _, trustedEmailAddress := range apiObjs {
		trustedEmailAddressId, trustedEmailAddressIdOk := trustedEmailAddress.GetIdOk()
		trustedEmailAddress, trustedEmailAddressOk := trustedEmailAddress.GetEmailAddressOk()

		if trustedEmailAddressIdOk && trustedEmailAddressOk {
			trustedEmailAddressData[*trustedEmailAddressId] = *trustedEmailAddress
		}
	}

	return trustedEmailAddressData, nil
}
