// Copyright © 2025 Ping Identity Corporation
// Code generated by ping-cli-generator

package resources

import (
	"fmt"

	"github.com/patrickcping/pingone-go-sdk-v2/management"
	"github.com/pingidentity/pingcli/internal/connector"
	"github.com/pingidentity/pingcli/internal/connector/common"
	"github.com/pingidentity/pingcli/internal/connector/pingone"
	"github.com/pingidentity/pingcli/internal/logger"
)

// Verify that the resource satisfies the exportable resource interface
var (
	_ connector.ExportableResource = &PingOneApplicationSignOnPolicyAssignmentResource{}
)

type PingOneApplicationSignOnPolicyAssignmentResource struct {
	clientInfo *connector.ClientInfo
}

// Utility method for creating a PingOneApplicationSignOnPolicyAssignmentResource
func ApplicationSignOnPolicyAssignment(clientInfo *connector.ClientInfo) *PingOneApplicationSignOnPolicyAssignmentResource {
	return &PingOneApplicationSignOnPolicyAssignmentResource{
		clientInfo: clientInfo,
	}
}

func (r *PingOneApplicationSignOnPolicyAssignmentResource) ResourceType() string {
	return "pingone_application_sign_on_policy_assignment"
}

func (r *PingOneApplicationSignOnPolicyAssignmentResource) ExportAll() (*[]connector.ImportBlock, error) {
	l := logger.Get()
	l.Debug().Msgf("Exporting all '%s' Resources...", r.ResourceType())

	importBlocks := []connector.ImportBlock{}

	applicationData, err := r.getApplicationData()
	if err != nil {
		return nil, err
	}

	for applicationId, applicationName := range applicationData {
		applicationSignOnPolicyAssignmentData, err := r.getApplicationSignOnPolicyAssignmentData(applicationId)
		if err != nil {
			return nil, err
		}

		for applicationSignOnPolicyAssignmentId, applicationSignOnPolicyAssignmentSignOnPolicyId := range applicationSignOnPolicyAssignmentData {
			applicationSignOnPolicyAssignmentName, applicationSignOnPolicyAssignmentNameOk, err := r.getSignOnPolicyName(applicationSignOnPolicyAssignmentSignOnPolicyId)
			if err != nil {
				return nil, err
			}

			if !applicationSignOnPolicyAssignmentNameOk {
				continue
			}

			commentData := map[string]string{
				"Application ID":                           applicationId,
				"Application Name":                         applicationName,
				"Application Sign On Policy Assignment ID": applicationSignOnPolicyAssignmentId,
				"Application Sign On Policy Assignment Sign On Policy Name": applicationSignOnPolicyAssignmentName,
				"Export Environment ID": r.clientInfo.PingOneExportEnvironmentID,
				"Resource Type":         r.ResourceType(),
			}

			importBlock := connector.ImportBlock{
				ResourceType:       r.ResourceType(),
				ResourceName:       fmt.Sprintf("%s_%s", applicationName, applicationSignOnPolicyAssignmentName),
				ResourceID:         fmt.Sprintf("%s/%s/%s", r.clientInfo.PingOneExportEnvironmentID, applicationId, applicationSignOnPolicyAssignmentId),
				CommentInformation: common.GenerateCommentInformation(commentData),
			}

			importBlocks = append(importBlocks, importBlock)
		}
	}

	return &importBlocks, nil
}

func (r *PingOneApplicationSignOnPolicyAssignmentResource) getApplicationData() (map[string]string, error) {
	applicationData := make(map[string]string)

	iter := r.clientInfo.PingOneApiClient.ManagementAPIClient.ApplicationsApi.ReadAllApplications(r.clientInfo.PingOneContext, r.clientInfo.PingOneExportEnvironmentID).Execute()
	apiObjs, err := pingone.GetManagementAPIObjectsFromIterator[management.ReadOneApplication200Response](iter, "ReadAllApplications", "GetApplications", r.ResourceType())
	if err != nil {
		return nil, err
	}

	for _, innerObj := range apiObjs {
		var (
			applicationId     *string
			applicationIdOk   bool
			applicationName   *string
			applicationNameOk bool
		)

		switch {
		case innerObj.ApplicationOIDC != nil:
			applicationId, applicationIdOk = innerObj.ApplicationOIDC.GetIdOk()
			applicationName, applicationNameOk = innerObj.ApplicationOIDC.GetNameOk()
		case innerObj.ApplicationSAML != nil:
			applicationId, applicationIdOk = innerObj.ApplicationSAML.GetIdOk()
			applicationName, applicationNameOk = innerObj.ApplicationSAML.GetNameOk()
		case innerObj.ApplicationExternalLink != nil:
			applicationId, applicationIdOk = innerObj.ApplicationExternalLink.GetIdOk()
			applicationName, applicationNameOk = innerObj.ApplicationExternalLink.GetNameOk()
		default:
			continue
		}

		if applicationIdOk && applicationNameOk {
			applicationData[*applicationId] = *applicationName
		}
	}

	return applicationData, nil
}

func (r *PingOneApplicationSignOnPolicyAssignmentResource) getApplicationSignOnPolicyAssignmentData(applicationId string) (map[string]string, error) {
	applicationSignOnPolicyAssignmentData := make(map[string]string)

	iter := r.clientInfo.PingOneApiClient.ManagementAPIClient.ApplicationSignOnPolicyAssignmentsApi.ReadAllSignOnPolicyAssignments(r.clientInfo.PingOneContext, r.clientInfo.PingOneExportEnvironmentID, applicationId).Execute()
	apiObjs, err := pingone.GetManagementAPIObjectsFromIterator[management.SignOnPolicyAssignment](iter, "ReadAllSignOnPolicyAssignments", "GetSignOnPolicyAssignments", r.ResourceType())
	if err != nil {
		return nil, err
	}

	for _, applicationSignOnPolicyAssignment := range apiObjs {
		applicationSignOnPolicyAssignmentId, applicationSignOnPolicyAssignmentIdOk := applicationSignOnPolicyAssignment.GetIdOk()
		applicationSignOnPolicyAssignmentSignOnPolicy, applicationSignOnPolicyAssignmentSignOnPolicyOk := applicationSignOnPolicyAssignment.GetSignOnPolicyOk()

		if applicationSignOnPolicyAssignmentIdOk && applicationSignOnPolicyAssignmentSignOnPolicyOk {
			applicationSignOnPolicyAssignmentSignOnPolicyId, applicationSignOnPolicyAssignmentSignOnPolicyIdOk := applicationSignOnPolicyAssignmentSignOnPolicy.GetIdOk()

			if applicationSignOnPolicyAssignmentSignOnPolicyIdOk {
				applicationSignOnPolicyAssignmentData[*applicationSignOnPolicyAssignmentId] = *applicationSignOnPolicyAssignmentSignOnPolicyId
			}
		}
	}

	return applicationSignOnPolicyAssignmentData, nil
}

func (r *PingOneApplicationSignOnPolicyAssignmentResource) getSignOnPolicyName(signOnPolicyId string) (string, bool, error) {
	signOnPolicy, response, err := r.clientInfo.PingOneApiClient.ManagementAPIClient.SignOnPoliciesApi.ReadOneSignOnPolicy(r.clientInfo.PingOneContext, r.clientInfo.PingOneExportEnvironmentID, signOnPolicyId).Execute()
	ok, err := common.HandleClientResponse(response, err, "ReadOneSignOnPolicy", r.ResourceType())
	if err != nil {
		return "", false, err
	}
	if !ok {
		return "", false, nil
	}

	if signOnPolicy != nil {
		signOnPolicyName, signOnPolicyNameOk := signOnPolicy.GetNameOk()

		if signOnPolicyNameOk {
			return *signOnPolicyName, true, nil
		}
	}

	return "", false, fmt.Errorf("unable to get sign-on policy name for sign-on policy ID: %s", signOnPolicyId)
}
