// Copyright © 2025 Ping Identity Corporation
// Code generated by ping-cli-generator

package resources

import (
	"fmt"

	"github.com/patrickcping/pingone-go-sdk-v2/management"
	"github.com/pingidentity/pingcli/internal/connector"
	"github.com/pingidentity/pingcli/internal/connector/common"
	"github.com/pingidentity/pingcli/internal/connector/pingone"
	"github.com/pingidentity/pingcli/internal/logger"
)

// Verify that the resource satisfies the exportable resource interface
var (
	_ connector.ExportableResource = &PingOneApplicationResource{}
)

type PingOneApplicationResource struct {
	clientInfo *connector.ClientInfo
}

// Utility method for creating a PingOneApplicationResource
func Application(clientInfo *connector.ClientInfo) *PingOneApplicationResource {
	return &PingOneApplicationResource{
		clientInfo: clientInfo,
	}
}

func (r *PingOneApplicationResource) ResourceType() string {
	return "pingone_application"
}

func (r *PingOneApplicationResource) ExportAll() (*[]connector.ImportBlock, error) {
	l := logger.Get()
	l.Debug().Msgf("Exporting all '%s' Resources...", r.ResourceType())

	importBlocks := []connector.ImportBlock{}

	applicationData, err := r.getApplicationData()
	if err != nil {
		return nil, err
	}

	for applicationId, applicationName := range applicationData {
		commentData := map[string]string{
			"Application ID":        applicationId,
			"Application Name":      applicationName,
			"Export Environment ID": r.clientInfo.PingOneExportEnvironmentID,
			"Resource Type":         r.ResourceType(),
		}

		importBlock := connector.ImportBlock{
			ResourceType:       r.ResourceType(),
			ResourceName:       applicationName,
			ResourceID:         fmt.Sprintf("%s/%s", r.clientInfo.PingOneExportEnvironmentID, applicationId),
			CommentInformation: common.GenerateCommentInformation(commentData),
		}

		importBlocks = append(importBlocks, importBlock)
	}

	return &importBlocks, nil
}

func (r *PingOneApplicationResource) getApplicationData() (map[string]string, error) {
	applicationData := make(map[string]string)

	iter := r.clientInfo.PingOneApiClient.ManagementAPIClient.ApplicationsApi.ReadAllApplications(r.clientInfo.PingOneContext, r.clientInfo.PingOneExportEnvironmentID).Execute()
	apiObjs, err := pingone.GetManagementAPIObjectsFromIterator[management.ReadOneApplication200Response](iter, "ReadAllApplications", "GetApplications", r.ResourceType())
	if err != nil {
		return nil, err
	}

	for _, innerObj := range apiObjs {
		var (
			applicationId     *string
			applicationIdOk   bool
			applicationName   *string
			applicationNameOk bool
		)

		switch {
		case innerObj.ApplicationOIDC != nil:
			applicationId, applicationIdOk = innerObj.ApplicationOIDC.GetIdOk()
			applicationName, applicationNameOk = innerObj.ApplicationOIDC.GetNameOk()
		case innerObj.ApplicationSAML != nil:
			applicationId, applicationIdOk = innerObj.ApplicationSAML.GetIdOk()
			applicationName, applicationNameOk = innerObj.ApplicationSAML.GetNameOk()
		case innerObj.ApplicationExternalLink != nil:
			applicationId, applicationIdOk = innerObj.ApplicationExternalLink.GetIdOk()
			applicationName, applicationNameOk = innerObj.ApplicationExternalLink.GetNameOk()
		default:
			continue
		}

		if applicationIdOk && applicationNameOk {
			applicationData[*applicationId] = *applicationName
		}
	}

	return applicationData, nil
}
