// Copyright © 2025 Ping Identity Corporation
// Code generated by ping-cli-generator

package resources_test

import (
	"fmt"
	"testing"

	"github.com/pingidentity/pingcli/internal/connector"
	"github.com/pingidentity/pingcli/internal/testing/testutils"
	"github.com/pingidentity/pingcli/internal/testing/testutils_resource"
	"github.com/pingidentity/pingcli/internal/testing/testutils_resource/pingone_sso_testable_resources"
)

func Test_SignOnPolicyAction(t *testing.T) {
	// TODO: Re-enable test after compleition of TRIAGE-26632
	t.SkipNow()

	clientInfo := testutils.GetClientInfo(t)

	tr := pingone_sso_testable_resources.SignOnPolicyAction(t, clientInfo)

	tr.CreateResource(t)
	defer tr.DeleteResource(t)

	signOnPolicyTr := tr.Dependencies[0]

	expectedImportBlocks := []connector.ImportBlock{
		{
			ResourceType: tr.ExportableResource.ResourceType(),
			ResourceName: fmt.Sprintf("%s_%s", signOnPolicyTr.ResourceInfo.CreationInfo[testutils_resource.ENUM_NAME], tr.ResourceInfo.CreationInfo[testutils_resource.ENUM_TYPE]),
			ResourceID:   fmt.Sprintf("%s/%s/%s", clientInfo.PingOneExportEnvironmentID, signOnPolicyTr.ResourceInfo.CreationInfo[testutils_resource.ENUM_ID], tr.ResourceInfo.CreationInfo[testutils_resource.ENUM_ID]),
		},
	}

	// Existing actions are generated, test subset.
	testutils.ValidateImportBlockSubset(t, tr.ExportableResource, &expectedImportBlocks)
}
