// Copyright © 2025 Ping Identity Corporation
// Code generated by ping-cli-generator

package pingone_platform_testable_resources

import (
	"testing"

	"github.com/patrickcping/pingone-go-sdk-v2/management"
	"github.com/pingidentity/pingcli/internal/connector"
	"github.com/pingidentity/pingcli/internal/connector/common"
	"github.com/pingidentity/pingcli/internal/connector/pingone/platform/resources"
	"github.com/pingidentity/pingcli/internal/testing/testutils_resource"
)

func AgreementLocalization(t *testing.T, clientInfo *connector.ClientInfo) *testutils_resource.TestableResource {
	t.Helper()

	return &testutils_resource.TestableResource{
		ClientInfo: clientInfo,
		CreateFunc: createAgreementLocalization,
		DeleteFunc: deleteAgreementLocalization,
		Dependencies: []*testutils_resource.TestableResource{
			Agreement(t, clientInfo),
		},
		ExportableResource: resources.AgreementLocalization(clientInfo),
	}
}

func createAgreementLocalization(t *testing.T, clientInfo *connector.ClientInfo, resourceType string, strArgs ...string) testutils_resource.ResourceInfo {
	t.Helper()

	if len(strArgs) != 1 {
		t.Errorf("Unexpected number of arguments provided to createAgreementLocalization(): %v", strArgs)

		return testutils_resource.ResourceInfo{}
	}
	agreementId := strArgs[0]

	request := clientInfo.PingOneApiClient.ManagementAPIClient.AgreementLanguagesResourcesApi.CreateAgreementLanguage(clientInfo.PingOneContext, clientInfo.PingOneExportEnvironmentID, agreementId)
	clientStruct := management.AgreementLanguage{
		Locale:      "en-US",
		DisplayName: "Language_1",
		Enabled:     true,
	}

	request = request.AgreementLanguage(clientStruct)

	resource, response, err := request.Execute()
	ok, err := common.HandleClientResponse(response, err, "CreateAgreementLanguage", resourceType)
	if err != nil {
		t.Errorf("Failed to execute PingOne client function\nResponse Status: %s\nResponse Body: %s\nError: %v", response.Status, response.Body, err)

		return testutils_resource.ResourceInfo{}
	}
	if !ok {
		t.Errorf("Failed to execute PingOne client function\nResponse Status: %s\nResponse Body: %s", response.Status, response.Body)

		return testutils_resource.ResourceInfo{}
	}

	return testutils_resource.ResourceInfo{
		DeletionIds: []string{
			agreementId,
			*resource.Id,
		},
		CreationInfo: map[testutils_resource.ResourceCreationInfoType]string{
			testutils_resource.ENUM_ID:     *resource.Id,
			testutils_resource.ENUM_LOCALE: resource.Locale,
		},
	}
}

func deleteAgreementLocalization(t *testing.T, clientInfo *connector.ClientInfo, resourceType string, ids ...string) {
	t.Helper()

	if len(ids) != 2 {
		t.Errorf("Unexpected number of arguments provided to deleteAgreementLocalization(): %v", ids)

		return
	}

	request := clientInfo.PingOneApiClient.ManagementAPIClient.AgreementLanguagesResourcesApi.DeleteAgreementLanguage(clientInfo.PingOneContext, clientInfo.PingOneExportEnvironmentID, ids[0], ids[1])

	response, err := request.Execute()
	ok, err := common.HandleClientResponse(response, err, "DeleteAgreementLanguage", resourceType)
	if err != nil {
		t.Errorf("Failed to execute PingOne client function\nResponse Status: %s\nResponse Body: %s\nError: %v", response.Status, response.Body, err)

		return
	}
	if !ok {
		t.Errorf("Failed to execute PingOne client function\nResponse Status: %s\nResponse Body: %s", response.Status, response.Body)

		return
	}
}
