// Copyright © 2025 Ping Identity Corporation
// Code generated by ping-cli-generator

package pingone_platform_testable_resources

import (
	"testing"
	"time"

	"github.com/patrickcping/pingone-go-sdk-v2/management"
	"github.com/pingidentity/pingcli/internal/connector"
	"github.com/pingidentity/pingcli/internal/connector/common"
	"github.com/pingidentity/pingcli/internal/connector/pingone/platform/resources"
	"github.com/pingidentity/pingcli/internal/testing/testutils_resource"
)

func AgreementLocalizationRevision(t *testing.T, clientInfo *connector.ClientInfo) *testutils_resource.TestableResource {
	t.Helper()

	return &testutils_resource.TestableResource{
		ClientInfo: clientInfo,
		CreateFunc: createAgreementLocalizationRevision,
		DeleteFunc: deleteAgreementLocalizationRevision,
		Dependencies: []*testutils_resource.TestableResource{
			AgreementLocalization(t, clientInfo),
		},
		ExportableResource: resources.AgreementLocalizationRevision(clientInfo),
	}
}

func createAgreementLocalizationRevision(t *testing.T, clientInfo *connector.ClientInfo, resourceType string, strArgs ...string) testutils_resource.ResourceInfo {
	t.Helper()

	if len(strArgs) != 2 {
		t.Errorf("Unexpected number of arguments provided to createAgreementLocalizationRevision(): %v", strArgs)

		return testutils_resource.ResourceInfo{}
	}
	agreementId := strArgs[0]
	agreementLocalizationId := strArgs[1]

	parsedTime, err := time.Parse(time.RFC3339, "2098-08-01T22:45:44.497Z")
	if err != nil {
		t.Errorf("Failed to parse time: %v", err)

		return testutils_resource.ResourceInfo{}
	}

	request := clientInfo.PingOneApiClient.ManagementAPIClient.AgreementRevisionsResourcesApi.CreateAgreementLanguageRevision(clientInfo.PingOneContext, clientInfo.PingOneExportEnvironmentID, agreementId, agreementLocalizationId)
	clientStruct := management.AgreementLanguageRevision{
		EffectiveAt:      parsedTime,
		RequireReconsent: false,
		Text:             "Test, test, test",
		ContentType:      "text/plain",
	}

	request = request.AgreementLanguageRevision(clientStruct)

	resource, response, err := request.Execute()
	ok, err := common.HandleClientResponse(response, err, "CreateAgreementLanguageRevision", resourceType)
	if err != nil {
		t.Errorf("Failed to execute PingOne client function\nResponse Status: %s\nResponse Body: %s\nError: %v", response.Status, response.Body, err)

		return testutils_resource.ResourceInfo{}
	}
	if !ok {
		t.Errorf("Failed to execute PingOne client function\nResponse Status: %s\nResponse Body: %s", response.Status, response.Body)

		return testutils_resource.ResourceInfo{}
	}

	return testutils_resource.ResourceInfo{
		DeletionIds: []string{
			agreementId,
			agreementLocalizationId,
			*resource.Id,
		},
		CreationInfo: map[testutils_resource.ResourceCreationInfoType]string{
			testutils_resource.ENUM_ID: *resource.Id,
		},
	}
}

func deleteAgreementLocalizationRevision(t *testing.T, clientInfo *connector.ClientInfo, resourceType string, ids ...string) {
	t.Helper()

	if len(ids) != 3 {
		t.Errorf("Unexpected number of arguments provided to deleteAgreementLocalizationRevision(): %v", ids)

		return
	}

	request := clientInfo.PingOneApiClient.ManagementAPIClient.AgreementRevisionsResourcesApi.DeleteAgreementLanguageRevision(clientInfo.PingOneContext, clientInfo.PingOneExportEnvironmentID, ids[0], ids[1], ids[2])

	response, err := request.Execute()
	ok, err := common.HandleClientResponse(response, err, "DeleteAgreementLanguageRevision", resourceType)
	if err != nil {
		t.Errorf("Failed to execute PingOne client function\nResponse Status: %s\nResponse Body: %s\nError: %v", response.Status, response.Body, err)

		return
	}
	if !ok {
		t.Errorf("Failed to execute PingOne client function\nResponse Status: %s\nResponse Body: %s", response.Status, response.Body)

		return
	}
}
