// Copyright © 2025 Ping Identity Corporation
// Code generated by ping-cli-generator

package pingone_platform_testable_resources

import (
	"testing"

	"github.com/patrickcping/pingone-go-sdk-v2/management"
	"github.com/pingidentity/pingcli/internal/connector"
	"github.com/pingidentity/pingcli/internal/connector/common"
	"github.com/pingidentity/pingcli/internal/connector/pingone"
	"github.com/pingidentity/pingcli/internal/connector/pingone/platform/resources"
	"github.com/pingidentity/pingcli/internal/testing/testutils_resource"
)

func GatewayRoleAssignment(t *testing.T, clientInfo *connector.ClientInfo) *testutils_resource.TestableResource {
	t.Helper()

	return &testutils_resource.TestableResource{
		ClientInfo: clientInfo,
		CreateFunc: createGatewayRoleAssignment,
		DeleteFunc: deleteGatewayRoleAssignment,
		Dependencies: []*testutils_resource.TestableResource{
			Gateway(t, clientInfo),
		},
		ExportableResource: resources.GatewayRoleAssignment(clientInfo),
	}
}

func createGatewayRoleAssignment(t *testing.T, clientInfo *connector.ClientInfo, resourceType string, strArgs ...string) testutils_resource.ResourceInfo {
	t.Helper()

	if len(strArgs) != 1 {
		t.Errorf("Unexpected number of arguments provided to createGatewayRoleAssignment(): %v", strArgs)

		return testutils_resource.ResourceInfo{}
	}
	gatewayId := strArgs[0]

	iter := clientInfo.PingOneApiClient.ManagementAPIClient.RolesApi.ReadAllRoles(clientInfo.PingOneContext).Execute()
	apiObjs, err := pingone.GetManagementAPIObjectsFromIterator[management.EntityArrayEmbeddedRolesInner](iter, "ReadAllRoles", "GetRoles", resourceType)
	if err != nil {
		t.Errorf("Failed to execute PingOne client function\nError: %v", err)

		return testutils_resource.ResourceInfo{}
	}
	if len(apiObjs) == 0 {
		t.Fatal("Failed to execute PingOne client function\n No built-in roles returned from ReadAllRoles()")
	}

	var (
		roleId   string
		roleName string
	)

	for _, role := range apiObjs {
		if role.Role != nil {
			if role.Role.Name != nil && *role.Role.Name == management.ENUMROLENAME_APPLICATION_OWNER {
				roleId = *role.Role.Id
				roleName = string(*role.Role.Name)

				break
			}
		}
	}

	request := clientInfo.PingOneApiClient.ManagementAPIClient.GatewayRoleAssignmentsApi.CreateGatewayRoleAssignment(clientInfo.PingOneContext, clientInfo.PingOneExportEnvironmentID, gatewayId)
	clientStruct := management.RoleAssignment{
		Role: management.RoleAssignmentRole{
			Id: roleId,
		},
		Scope: management.RoleAssignmentScope{
			Id:   clientInfo.PingOneExportEnvironmentID,
			Type: "ENVIRONMENT",
		},
	}

	request = request.RoleAssignment(clientStruct)

	resource, response, err := request.Execute()
	ok, err := common.HandleClientResponse(response, err, "CreateGatewayRoleAssignment", resourceType)
	if err != nil {
		t.Errorf("Failed to execute PingOne client function\nResponse Status: %s\nResponse Body: %s\nError: %v", response.Status, response.Body, err)

		return testutils_resource.ResourceInfo{}
	}
	if !ok {
		t.Errorf("Failed to execute PingOne client function\nResponse Status: %s\nResponse Body: %s", response.Status, response.Body)

		return testutils_resource.ResourceInfo{}
	}

	return testutils_resource.ResourceInfo{
		DeletionIds: []string{
			gatewayId,
			*resource.Id,
		},
		CreationInfo: map[testutils_resource.ResourceCreationInfoType]string{
			testutils_resource.ENUM_ID:   *resource.Id,
			testutils_resource.ENUM_NAME: roleName,
		},
	}
}

func deleteGatewayRoleAssignment(t *testing.T, clientInfo *connector.ClientInfo, resourceType string, ids ...string) {
	t.Helper()

	if len(ids) != 2 {
		t.Errorf("Unexpected number of arguments provided to deleteGatewayRoleAssignment(): %v", ids)

		return
	}

	request := clientInfo.PingOneApiClient.ManagementAPIClient.GatewayRoleAssignmentsApi.DeleteGatewayRoleAssignment(clientInfo.PingOneContext, clientInfo.PingOneExportEnvironmentID, ids[0], ids[1])

	response, err := request.Execute()
	ok, err := common.HandleClientResponse(response, err, "DeleteGatewayRoleAssignment", resourceType)
	if err != nil {
		t.Errorf("Failed to execute PingOne client function\nResponse Status: %s\nResponse Body: %s\nError: %v", response.Status, response.Body, err)

		return
	}
	if !ok {
		t.Errorf("Failed to execute PingOne client function\nResponse Status: %s\nResponse Body: %s", response.Status, response.Body)

		return
	}
}
