// Copyright © 2025 Ping Identity Corporation
// Code generated by ping-cli-generator

package pingone_platform_testable_resources

import (
	"testing"

	"github.com/patrickcping/pingone-go-sdk-v2/management"
	"github.com/pingidentity/pingcli/internal/connector"
	"github.com/pingidentity/pingcli/internal/connector/common"
	"github.com/pingidentity/pingcli/internal/connector/pingone/platform/resources"
	"github.com/pingidentity/pingcli/internal/testing/testutils_resource"
	"github.com/pingidentity/pingcli/internal/utils"
)

func NotificationTemplateContent(t *testing.T, clientInfo *connector.ClientInfo) *testutils_resource.TestableResource {
	t.Helper()

	return &testutils_resource.TestableResource{
		ClientInfo:         clientInfo,
		CreateFunc:         createNotificationTemplateContent,
		DeleteFunc:         deleteNotificationTemplateContent,
		Dependencies:       nil,
		ExportableResource: resources.NotificationTemplateContent(clientInfo),
	}
}

func createNotificationTemplateContent(t *testing.T, clientInfo *connector.ClientInfo, resourceType string, strArgs ...string) testutils_resource.ResourceInfo {
	t.Helper()

	if len(strArgs) != 0 {
		t.Errorf("Unexpected number of arguments provided to createNotificationTemplateContent(): %v", strArgs)

		return testutils_resource.ResourceInfo{}
	}

	request := clientInfo.PingOneApiClient.ManagementAPIClient.NotificationsTemplatesApi.CreateContent(clientInfo.PingOneContext, clientInfo.PingOneExportEnvironmentID, management.ENUMTEMPLATENAME_STRONG_AUTHENTICATION)
	clientStruct := management.TemplateContent{
		TemplateContentSMS: &management.TemplateContentSMS{
			Locale:         "en",
			Variant:        utils.Pointer("variant_C"),
			Content:        "${user.username} your one time password is ${otp}.",
			DeliveryMethod: "SMS",
			Default:        utils.Pointer(false),
		},
	}

	request = request.TemplateContent(clientStruct)

	resource, response, err := request.Execute()
	ok, err := common.HandleClientResponse(response, err, "CreateContent", resourceType)
	if err != nil {
		t.Errorf("Failed to execute PingOne client function\nResponse Status: %s\nResponse Body: %s\nError: %v", response.Status, response.Body, err)

		return testutils_resource.ResourceInfo{}
	}
	if !ok {
		t.Errorf("Failed to execute PingOne client function\nResponse Status: %s\nResponse Body: %s", response.Status, response.Body)

		return testutils_resource.ResourceInfo{}
	}

	return testutils_resource.ResourceInfo{
		DeletionIds: []string{
			*resource.TemplateContentSMS.Id,
		},
		CreationInfo: map[testutils_resource.ResourceCreationInfoType]string{
			testutils_resource.ENUM_ID:                       *resource.TemplateContentSMS.Id,
			testutils_resource.ENUM_NAME:                     string(management.ENUMTEMPLATENAME_STRONG_AUTHENTICATION),
			testutils_resource.ENUM_LOCALE:                   resource.TemplateContentSMS.Locale,
			testutils_resource.ENUM_TEMPLATE_VARIANT:         *resource.TemplateContentSMS.Variant,
			testutils_resource.ENUM_TEMPLATE_DELIVERY_METHOD: string(resource.TemplateContentSMS.DeliveryMethod),
		},
	}
}

func deleteNotificationTemplateContent(t *testing.T, clientInfo *connector.ClientInfo, resourceType string, ids ...string) {
	t.Helper()

	if len(ids) != 1 {
		t.Errorf("Unexpected number of arguments provided to deleteNotificationTemplateContent(): %v", ids)

		return
	}

	request := clientInfo.PingOneApiClient.ManagementAPIClient.NotificationsTemplatesApi.DeleteContent(clientInfo.PingOneContext, clientInfo.PingOneExportEnvironmentID, management.ENUMTEMPLATENAME_STRONG_AUTHENTICATION, ids[0])

	response, err := request.Execute()
	ok, err := common.HandleClientResponse(response, err, "DeleteContent", resourceType)
	if err != nil {
		t.Errorf("Failed to execute PingOne client function\nResponse Status: %s\nResponse Body: %s\nError: %v", response.Status, response.Body, err)

		return
	}
	if !ok {
		t.Errorf("Failed to execute PingOne client function\nResponse Status: %s\nResponse Body: %s", response.Status, response.Body)

		return
	}
}
