= pingcli pingfederate
:created-date: May 15, 2026
:revdate: May 15, 2026
:resourceid: pingcli_command_reference_pingcli_pingfederate

Administration tools for PingFederate deployed as software

== Synopsis

Administration tools for PingFederate deployed as software.
		
When multiple products are configured in the CLI, the platform command can be used to manage one or more products collectively.

The --profile command switch can be used to specify the profile of Ping products to be managed.

----
pingcli pingfederate
----

== Options inherited from parent commands

----
  -C, --config string           The relative or full path to a custom Ping CLI configuration file. (default $HOME/.pingcli/config.yaml)
  -D, --detailed-exitcode       Enable detailed exit code output. (default false) 0 - pingcli command succeeded with no errors or warnings. 1 - pingcli command failed with errors. 2 - pingcli command succeeded with warnings.
  -O, --output-format string    Specify the console output format. (default text) Options are: json, ndjson, text.
  -P, --profile string          The name of a configuration profile to use.
      --debug                   Enable debug output for error messages, including stack traces and transaction IDs. (default false)
      --log-file string         Write logs to a file at the given path. File logging is disabled when not set.
      --log-file-level string   Set the file log level. Options are: DEBUG, INFO, WARN, ERROR. (default DEBUG)
      --log-level string        Set the console log level. Options are: DEBUG, INFO, WARN, ERROR. (default WARN)
      --no-color                Disable text output in color. (default false)
----

== More information

* xref:pingcli.adoc[]	 - A CLI tool for managing the configuration of Ping Identity products.

== Subcommands

* xref:pingcli_pingfederate_api.adoc[] - Send a custom REST API request to the management API of PingFederate.
* xref:pingcli_pingfederate_auth.adoc[] - Authenticate Ping CLI to the PingFederate management APIs.
* xref:pingcli_pingfederate_init.adoc[] - Initialize Ping CLI for the PingFederate management APIs.
