= pingcli
:created-date: May 15, 2026
:revdate: May 15, 2026
:resourceid: pingcli_command_reference_pingcli

A CLI tool for managing the configuration of Ping Identity products.

== Synopsis

A CLI tool for managing the configuration of Ping Identity products.

----
pingcli
----

== Options

----
  -C, --config string           The relative or full path to a custom Ping CLI configuration file. (default $HOME/.pingcli/config.yaml)
  -h, --help                    help for pingcli
  -D, --detailed-exitcode       Enable detailed exit code output. (default false) 0 - pingcli command succeeded with no errors or warnings. 1 - pingcli command failed with errors. 2 - pingcli command succeeded with warnings.
  -O, --output-format string    Specify the console output format. (default text) Options are: json, ndjson, text.
  -P, --profile string          The name of a configuration profile to use.
      --debug                   Enable debug output for error messages, including stack traces and transaction IDs. (default false)
      --log-file string         Write logs to a file at the given path. File logging is disabled when not set.
      --log-file-level string   Set the file log level. Options are: DEBUG, INFO, WARN, ERROR. (default DEBUG)
      --log-level string        Set the console log level. Options are: DEBUG, INFO, WARN, ERROR. (default WARN)
      --no-color                Disable text output in color. (default false)
----

== Subcommands

* xref:pingcli_advanced-services.adoc[] - Administration tools for the PingOne Advanced Services private tenant.
* xref:pingcli_agent-skills.adoc[] - Find and install agent skills for Ping CLI.
* xref:pingcli_auth.adoc[] - Authenticate (or refresh authentication) for multiple connected products and services at once.
* xref:pingcli_completion.adoc[] - Prints shell completion scripts
* xref:pingcli_config.adoc[] - Manage the CLI configuration.
* xref:pingcli_davinci.adoc[] - Administration tools for the PingOne DaVinci universal service.
* xref:pingcli_feedback.adoc[] - Help us improve the CLI. Report issues or send us feedback on using the CLI tool.
* xref:pingcli_identity-cloud.adoc[] - Administration tools for the PingOne Advanced Identity Cloud private tenant.
* xref:pingcli_init.adoc[] - Initialize Ping CLI with a guided setup wizard.
* xref:pingcli_pingfederate.adoc[] - Administration tools for PingFederate deployed as software
* xref:pingcli_pingone.adoc[] - Administration tools for the PingOne platform.
